### ISSUE TITLE
kollwi / Wenn neues Dokument gespeichert, erscheinen Attribute erst bei Klick auf "a"

### ISSUE THREAD

**Issue by gstangl** [substance/substance-legacy#10]
Obwohl das Dokument gespeichert wurde schaut es so aus:
http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-04%20at%2019.31.26.png

Erst wenn "a" geklickt wurde schaut es richtig, also so aus:
http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-04%20at%2019.31.37.png

**Comment by michael** [comment]
Jupp. Ich weiß. Da müssma einen expliziten refresh des attribute editors machen. Mach ich bei nächster Gelegenheit.

**Comment by michael** [comment]
Fixed.
