### ISSUE TITLE
Your thing deleted all my work.

### ISSUE THREAD

**Issue by blaine** [substance/substance-legacy#100]
Suck. :-(

I think something got out of sync. It looked like everything was saving, but it wasn't. And now all my work is gone.

**Comment by michael** [comment]
Ah sh*t :/

It happend to me too some time ago, but I couldn't reproduce it at all. If you could somehow reproduce the problem, I'll do all I can to get it fixed.

I'm so sorry for the text you lost :(

Hint: You should hit reload regularly to make sure if everything is updating fine.

**Comment by blaine** [comment]
I think the problem was that I'd opened the document to view it early on in the process in another window, and that confused things. I'm not sure at all what happened, but I think the problem for me was that I saw the regular "save" indicator flashing on the page, but it clearly was either saving something other than what was being displayed, or not actually saving. If it had shown some kind of error / "can't save" message instead of the reassuring "still saving" indicator, I would have caught it much earlier. :-/

Is it possible that there's something saved on the server? I haven't dug into the code yet to see if it would have saved remotely, even if the data wasn't being recorded. Alternatively, any tips for where to start looking in the local storage / cookies? A cursory inspection didn't reveal anything.

Sorry for the curt message – I was just at the end of my day and had to run, but was feeling frustrated. Overall, Substance is one of the nicest projects I've seen in quite some time, and I'm quite keen to keep using it. :-)

**Comment by max-mapper** [comment]
this just happened to me too, hehe. can't wait for the localstorage stuff to get deployed :D

**Comment by michael** [comment]
@blaine What's your user and the name of the doc? Will look it up in the db if I can restore some fragments that have been persisted.

No worries man, I can literally feel your pain. Putting together sentences is hard enough.

Let's try to reproduce it and finally fix it. Maybe you can figure out what steps need to be taken to make it fail (based a new doc). I'm already catching and handling some exceptions (like when a conflict occurs, or the session is invalid) but it's obvious that I missed something.

**Comment by max-mapper** [comment]
@michael I think I have a live one! on the same document that I lost data on earlier, if I add a new section, the uploading spinner appears and then disappears and the XHR log says that a PUT to `/graph/write` returned `{status":"ok","graph": ...}`. if I reload the new section is gone :(. document id is `mobile-crowdsourcing-interfaces`

**Comment by michael** [comment]
Mhh, I guess the problem here isn't the sync, but the local graph manipulation triggered by the UI. The local graph gets into an undesired state, then persisted. Ideally, I'd have this reproduced with a new document. However I'll try play around with your doc (in a local sandbox).

**Comment by michael** [comment]
Seems like empty sections aren't synced at all. And I stumbled upon another error.
1. create a new doc
2. create a new section (and name it)
3. delete that section

After the sync the deleted section remains referenced by the document, and leads to an error (reload). Will do some (hopefully happy) bugfixing tomorrow.

**Comment by michael** [comment]
@maxogden The problem you described resulted from a regression bug. https://github.com/michael/substance/commit/e9b35d59865cc9b4a2ce07a209bfe702808b7a24

Not sure about what exactly happened to @blaine though. Having the doc open in multiple windows can definitely be problematic. However I'm doing some safety checks already. Try creating a new doc, open it a second time and start editing in both windows. You should receive an error message: "There are conflicted or rejected nodes since the last sync. The workspace will be reset for your own safety".
