### ISSUE TITLE
ability to modify date of document

### ISSUE THREAD

**Issue by max-mapper** [substance/substance-legacy#102]
yo michael,

can you expose a way to update the created_at date so that blogposts can be backdated when ported to substance?

cheers,

max

**Comment by boazsender** [comment]
+1

**Comment by michael** [comment]
Hey. In the reader, docs are sorted by "updated_at". I guess you want to order by "published_on" ? You need to change the corresponding code at: https://github.com/michael/reader/blob/master/javascripts/application.js#L24

Will support explicitly setting published_on through the UI. But until then, you can can do it using the Data.js API.

In the Substance workspace, open the console and type:

```
graph.get(app.document.model._id).set({published_on: new Date(YYYY, MM, DD)};
```

**Comment by michael** [comment]
Belongs to 0.4.0 series. Closing.
