### ISSUE TITLE
Something wrong with couch-client.js?

### ISSUE THREAD

**Issue by itguy51** [substance/substance-legacy#105]
When I attempt to login via the interface, It fails, and then the console spits out 

Performing query:
{ _id: [], subjects: {}, entities: {}, creator: {} }
Performing query:
{ type: '/type/user' }
{ stack: [Getter/Setter],
  arguments: [ 'views', undefined ],
  type: 'non_object_property_load',
  message: [Getter/Setter] }
TypeError: Cannot read property 'views' of undefined
    at Array.0 (/root/el/substance/lib/data/adapters/couch_adapter.js:272:22)
    at /root/el/substance/lib/data/lib/couch-client.js:176:24
    at Array.forEach (native)
    at /root/el/substance/lib/data/lib/couch-client.js:171:22
    at IncomingMessage.<anonymous> (/root/el/substance/lib/data/lib/couch-client.js:76:25)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1231:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

Is this a normal piece of behavior? (I am running the DB on a non-standard port...)

**Comment by michael** [comment]
You probably forgot to seed the database — setting up schema information.

```
node db/seed.js
```

Then Substance specific static views:

```
cake couch:push
```

**Comment by itguy51** [comment]
I changed it a little, so that the config.json file would not have to be edited (Run CouchDB on the standard port, and Substance as the DB name, executed all of those, now I get the error of 

```
Performing query:
{ _id: [], subjects: {}, entities: {}, creator: {} }
Performing query:
{ type: '/type/user' }
WARNING: No index could be found for this query:
{}
```

when I try to login. The bottom right corner has an error message that reads "Authentication failed."

Is the error within Substance or is it in CouchDB?
I know that CouchDB does have a small bit of different behavior in the version I am using, as it is the newest version. Do you mind me asking what version of Couch you use on the substance.io domain?

**Comment by itguy51** [comment]
Recent Push to Github fixed this issue. Thank you!

**Comment by michael** [comment]
KK :) Sorry I couldn't reproduce it.

**Comment by itguy51** [comment]
No problems. I guess it was just my configuration.
