### ISSUE TITLE
Offenes Dokument kann nicht aus Dashboard geöffnet werden.

### ISSUE THREAD

**Issue by gstangl** [substance/substance-legacy#11]
Das selbe Dokument das gerade offen ist kann nicht via Klick im Dashboard geöffnet werden:
http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-04%20at%2020.30.03.png

**Comment by michael** [comment]
Das ist ein interessanter Sonderfall. Ich glaub was in diesem Fall passieren sollte, ist dass man einfach in die Dokumentansicht wechselt, jedoch ohne das Dokument neu zu laden. Würde er es neu laden würden eventuelle Änderungen verworfen werden. Überleg mir was.

**Comment by michael** [comment]
Solved. Should now work in current development version.
