### ISSUE TITLE
Image upload not working for me

### ISSUE THREAD

**Issue by brianshumate** [substance/substance-legacy#117]
First, let me say that this is amazing software, and I thank you for creating it.

I've installed and configured Substance without a hitch on a Linux machine with the following versions:
- Ubuntu 10.04LTS
- Node.JS 0.4.11
- CouchDB 1.0.2 (running on on a second machine and accessible through a non-routable network)

I've signed up for transloadit and have entered my API key into `config.json`.

Everything else works well for me, but the image upload behaves the same way consistently across any WebKit based browser.

Either the dialog hangs at 0% or 4% completed and the image is never fully processed or uploaded each time. I've tried in multiple documents and with various JPG and PNG images from 127K down to 48KB. I've disabled the Nginx in front of the app and accessed it directly on port 3003, but it still behaves the same way.

UPDATE: I just upgraded to Node 0.4.12, restarted the app and the first upload of a 74KB JPG appeared as though it was going to work, but wedged at 85% this time. :(

FWIW, there are no obvious errors being emitted from the app or to CouchDB's log.

Any ideas or tips for further debugging my issue?

Thanks!

**Comment by michael** [comment]
You need to setup a proper template for the transloadit robot. Here's how mine looks like:

```
{
  "auth": {
    "key": "your_key"
  },
  "steps": {
    "web_version": {
      "use": ":original",
      "robot": "/image/resize",
      "width": 720,
      "height": 1000,
      "zoom": false,
      "format": "png",
      "result": true
    },
    "print_version": {
      "use": ":original",
      "robot": "/image/resize",
      "width": 2000,
      "height": 2000,
      "zoom": false,
      "format": "png",
      "result": true
    },
    "store": {
      "use": ["web_version", "print_version"],
      "robot": "/s3/store",
      "bucket": "substance-assets",
      "key": "s3-key",
      "secret": "s3-secret"
    }
  },
  "redirect_url": "http://substance.io"
}
```

Be aware that you also need to specify where to store the images (transloadit does just the conversion). In my case its an Amazon S3 bucket.

However, even at substance.io image upload fails sometimes. Couldn't find out yet what's the cause.

**Comment by brianshumate** [comment]
Aha, sorry about missing that. Thanks again!

**Comment by michael** [comment]
Tell me if it worked for you — will add it to the installation instructions then.

**Comment by brianshumate** [comment]
Sorry, I configured and tested in transloadit and the template worked!

I returned to clean up the failed uploads from my document. After removing 4 failed uploads from the document structure and allowing the updates to happen (waiting for the spinner), I stopped the app and added my template id to the `config.json`.

I was excited to try uploading an image, but when I attempted to access my document, it is now broken/behaves as though its empty, which I suppose might be related to #100.

I did confirm everything still exists in CouchDB, though.

I guess today's just not my day to work on this document. :( I will try again later.

**Comment by michael** [comment]
What does the console say, when accessing the document? I added some debug output, if there are content node references that can't be reached. Based on that information you can manually repair your document.

## 

If you can reproduce the error with a new document, please give me a detailed bug report and I'll fix it.

**Comment by brianshumate** [comment]
When I access the document in question, I see this:

```
Performing query:
{ _id: '/document/brianshumate/d26c4309f689dface08eed74ffddc0c7',
  children: { _recursive: true, comments: {} },
  subjects: {},
  entities: {},
  creator: {} }
Performing query:
{ type: '/type/subscription',
  document: '/document/brianshumate/d26c4309f689dface08eed74ffddc0c7' }
```

I'll try again with starting everything over from scratch later. Thanks again for your help! :)

**Comment by michael** [comment]
Sorry, the browser's console is what i meant. ;)

**Comment by brianshumate** [comment]
D'oh! :/

I understand what you mean, now. Alas, the document I am concerned with does not show any references; the console only outputs `TypeError: 'undefined' is not an object (evaluating 'child.type._id')` when I access it.

I do have a second document which I don't really care about at all that is in the same state, but accessing that one does actually print a reference to the console.

None of these data are critical to me, however so it's no big deal. If it would be helpful, I am happy to provide the database or any other information I can.
