### ISSUE TITLE
Store Images and Files Locally

### ISSUE THREAD

**Issue by itguy51** [substance/substance-legacy#119]
Is this possible? If so, I would think it would be useful, or use a free image storage system, as I don't want to have to pay for not only my S3, but Transloadit as well, I am implementing something and it will handle tens of gigabytes of images daily, and for no cost whatsoever. I don't want to adify the pages either, so I would like to see the images stored locally, Which would, technically be on my S3, but I don't want to pay for simple resizing, it seems like a bad idea when images can actually be resized for free locally for some users.

**Comment by michael** [comment]
Sure, that could be implemented. I just wanted to avoid the hassle and save time by consuming services. @transloadit sponsered image processing for Substance.io.

However feel free to do the processing yourself.

**Comment by itguy51** [comment]
Ah. I don't know where the processing takes place, is it server-side or client-side, and what file implements it?

**Comment by michael** [comment]
It's all client-side. Here's the corresponding code: https://github.com/michael/substance/blob/master/src/client/node_editors/image_editor.js#L27

**Comment by itguy51** [comment]
Great! I'll take a look at it and how I would implement it via NodeJS
