### ISSUE TITLE
Gelöschte Dokumente tauchen wieder auf.

### ISSUE THREAD

**Issue by gstangl** [substance/substance-legacy#12]
Gelöschte Dokumente tauchen immer wieder auf. 
Das hier zum Beispiel hab ich schon zwei Mal gelöscht:
http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-04%20at%2020.34.29.png

**Comment by gstangl** [comment]
also sie tauchen erst beim Reload wieder auf. Vorher sind sie vorerst schon mal weg.

**Comment by michael** [comment]
mhh dann haut das löschen nicht hin. schau ich mir an

**Comment by michael** [comment]
aber löschen is eh viel zu gefährlich =)

**Comment by michael** [comment]
Tritt das noch immer auf? Haut bei mir soweit hin. Falls alles funktioniert, bitte Ticket zumachen. -- Michael
