### ISSUE TITLE
User registration error

### ISSUE THREAD

**Issue by mavimo** [substance/substance-legacy#129]
I'm try to install substance with:
- Ubuntu 11.04
- Apache CouchDB 1.1.0
- Node 0.4.12

After I have executed command indicated on internal -> installation guide seam it work (i can see home page, i can go into different page like Forgot password, register), but if I try to create a new account i can submit data, but there are not response from server and after a logn time i recive "Undefined error"

Anyone have the same problem?

**Comment by michael** [comment]
Did you perform a db seed first

```
$ node db/seed.js --flush
```

and then push the CouchApp?

```
$ cake couch:push
```

Also check in your config file if there are settings for the transloadit service provided:

```
{
  "couchdb_url": "http://localhost:5984/substance",
  "server_host": null,
  "server_url": "http://localhost:3003",
  "secret": "super secret",
  "server_port": 3003,
  "transloadit": {
    "auth": {
      "key": "your_key"
    },
    "template_id": "your_template",
    "redirect_url": "http://substance.io"
  }
}
```

**Comment by mavimo** [comment]
I execute:

``` bash
$ node db/sed.jss --flush
$ cacke couch:push
```

and I haven't any error.

My settings are:

``` javascript
{
  "couchdb_url": "http://admin:admin123@localhost:5984/substance",
  "server_host": null,
  "server_port": 3003,
  "secret": "21f1b334fcf48788113c70a0103fad8a",
  "transloadit": {
    "auth": {
      "key": "21f1b334fcf48788113c70a0103fad8a"
    },
    "template_id": "your_template_id",
    "redirect_url": "http://localhost:3003"
  }
}
```

but it don't work, can you help me to find how to debug this error?

**Comment by michael** [comment]
What is the server log saying? Can you point me to the file and line where the error occurs?

**Comment by mavimo** [comment]
No error are visible in node log, but CouchDB log write:

```
root@supernova:/home/marco/Development/git/substance# tail -n 20 /var/log/couchdb/couch.log 
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3912.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3915.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3918.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3921.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3924.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3927.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3930.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3933.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3936.40> :: {os_process_error,
                                                       {exit_status,127}}
[Sun, 09 Oct 2011 13:15:35 GMT] [error] [<0.27675.6>] OS Process Error <0.3939.40> :: {os_process_error,
                                                       {exit_status,127}}
```

**Comment by michael** [comment]
Argh. Super-strange. Haven't had that one yet. So your CouchDB installation is working then — you can create/update/delete CouchDB documents?

**Comment by mavimo** [comment]
I try to add a new database using CURL and ork fine (using admin login, as specified in config.json):

``` bash
marco@supernova:~$ curl -X GET http://127.0.0.1:5984/_all_dbs
["_replicator","_users","substance"]
marco@supernova:~$ curl -X PUT http://admin:admin123@127.0.0.1:5984/baseball
{"ok":true}
marco@supernova:~$ curl -X GET http://127.0.0.1:5984/_all_dbs
["_replicator","_users","baseball","substance"]
```

Substance can use authentication from connection string? Have you got some command to test/create a user from CLI?

Thanks!

**Comment by michael** [comment]
The justified CouchClient library Data.js uses should basically support authentication, but this isn't tested yet. Thus far I'm running all my stuff in admin party mode, having CouchDB bound to 127.0.0.1. Please try again without auth, I guess this will solve your problem.

**Comment by mavimo** [comment]
I rollback to Couch 1.0.1 and no auth, but it still doesn't work.

Before downgrade also data.js example (tasks) don't work, now it work fine, but i can't add user using substance.

**Comment by michael** [comment]
Mhh.. really strange. And you don't get any errors at the server console?

You could manually create a user right in the Futon admin panel, if it's just the user registration that doesn't work.

```
{
  "_id": "/user/test",
  "created_at": "2011-10-01T16:22:47.445Z",
  "type": ["/type/user"],
  "name": "Test User",
  "email": "test@domain.com",
  "username": "test",
  "password": // you need to encrypt it using a sha256 hash.
}
```

**Comment by mavimo** [comment]
After manually adding a _test_ user I can login and edit user information, but I can't create new user from UI. I'll try to debug why it don't work.
Node console write:

```
GET /client/views/application.js
Performing query:
{ type: '/type/user' }
WARNING: No index could be found for this query:
{}
```

On registrate a new user (with name _marco_) I can see in CouchDB log:

```
[Sun, 09 Oct 2011 20:53:36 GMT] [info] [<0.17305.0>] 127.0.0.1 - - 'GET' /substance/_design/substance/_view/users?key=%22marco%22 404
```

I tink there are some error; using Fution i can't see **_design/substance/_view/users** definition

**Comment by michael** [comment]
Mhh that should have been setup by:

```
$ cake couch:push
```

**Comment by mavimo** [comment]
Also writing docs fail :'(

**Comment by mavimo** [comment]
I completly drop DB, re-run:

``` bash
node db/seed.js --flush
cake couch:push # two time!
```

and now.. it work!!! :)

Thanks for support!

Now.. I can start to study your code ;)
