### ISSUE TITLE
creating links in a text (and get them stored)

### ISSUE THREAD

**Issue by ingoradatz** [substance/substance-legacy#130]
# problem

I insert a link (refers to an anker in the same document) in a text of a sub-section and it works well in the edit mode. If i switch to the view mode the link is taken away from the text (then also if  switch back to edit mode).

I figure out that the html for the link is correctly inserted from the ui. So the solution have to be in a other part of the software?
# howto reproduce it

my browser is a chrome 14

edit mode >> text element >> enter text >> mark the name of the link (e.g. a word) >> klick link and fill the url alert >> leave the edit mode of the text element (wysiwyg editor hides) >> fine

enter the view mode >> click the link >> fail? (link doesnt exists?)
# workaround

Paste a url from clipboard in a text element and get a link with a huge linktext (the url). Then change the linktext somewhere in the middle and remove the wrapping text on both sides -> fine

**Comment by timjb** [comment]
I think the problem is our HTML sanitizer. It tries to filter out `<a href="javascript:maliciousCode()">` by using a whitelist for the value of the href attribute. I will add a rule for linking to anchors.

**Comment by michael** [comment]
Just deployed that fix.

**Comment by ingoradatz** [comment]
ok, but one question remains: why does the same link href passed the sanitizer if i copy/paste the url directly in the text (and it automatically generate a link)?

**Comment by timjb** [comment]
Well, I just found out about the link auto detection. That seems to be a feature of contenteditable. I have really no idea why your link passed through the sanitizer. Can you paste your url (or one that is similar in structure) please?

**Comment by ingoradatz** [comment]
http://www.substance.io/USERNAME/DOCNAME/_section_SECTIONID :-)

**Comment by timjb** [comment]
This URL has always been valid. My commit fixes links to anchors like `#_section_SECTIONID`. Btw, does it work now?

**Comment by ingoradatz** [comment]
yes, it does

It seems to exists an other issue. If I set the link and switch to read-mode for testing - sometimes the href is lost (perhaps it is a side effect of the syncing process). I think, its not a question in this topic and if i sure what happens i will create a separate topic.

thank you
