### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by mmichelli** [substance/substance-legacy#131]
Any plans on adding a taxonomy tree? 

I have a lot of uses for this project if it has kind of flexible content structuring.

**Comment by timjb** [comment]
Do you mean something like this?

![this Drupal module](http://drupal.org/files/images/taxonomy_tree_select-6.x-alpha3.preview.png)

**Comment by mmichelli** [comment]
Yes, really usefully for newspapers.

**Comment by michael** [comment]
We're rather planning to use faceted classification, using the concept of a "Network".

Read on here: 
https://groups.google.com/forum/?hl=de#!topic/substance_/ZYGdXZ7PU0U

**Comment by mmichelli** [comment]
I like the idea of substance.io/lybia being a channel. 

I guess you could have an article live in a channel and have a taxonomy for building external websites.

**Comment by michael** [comment]
Exactly, so a taxonomy could sit on top of "networks" or "channels". Not set on the name yet. Suggestions? :)

**Comment by mmichelli** [comment]
I think the name is more a question of interaction design, how you want the system to be used in the future.   

Channel = describes how users will subscribe to it 
Stream = describes how users will choose what content flows to them 
Network = describes how users will be connected to a topic and group of people 

After writing the above I like 'network' because of the network of people.
