### ISSUE TITLE
Table creation

### ISSUE THREAD

**Issue by mavimo** [substance/substance-legacy#133]
Hello,
  more paper require table data structure I think that's possible implement it as node (_/type/table_ ?).

There are some reasons why it has not been implemented?

**Comment by michael** [comment]
Just one reason: Time ;)

You're welcome to help out here. You can come up with some some UI sketches or with a first implementation. Any support helps. :)

I think we should go with basic functionality first: 
- add/remove rows/columns
- column headers (optional)

-- Michael

**Comment by michael** [comment]
FYI: We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
