### ISSUE TITLE
Editor: 'Move section' and 'remove node' problems

### ISSUE THREAD

**Issue by keybits** [substance/substance-legacy#136]
Substance looks fantastic - I am very impressed.  From reading the mailing list and issues I realise the editor is not top priority at the moment, but just to register the issues I have:
- Move section: Dragging the four headed arrow does now allow me to move a section reliably elsewhere (tried in various browsers)
- Remove node: If I just want to remove a section heading I cannot do so without removing the text below that is in the same node

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
