### ISSUE TITLE
Have document I cannot load nor delete

### ISSUE THREAD

**Issue by polandj** [substance/substance-legacy#138]
I have a document that when I click on it to load, it doesn't give any error but also doesn't fully load.  The location and the url change, the document and the normal menu doesn't ever load.

**Comment by michael** [comment]
Can you publish it and share the URL of that particular document?

**Comment by polandj** [comment]
Unfortunately, because it doesn't open, I can't publish it.  I've 
attached a screenshot of what happens.  doclist is what I see when I 
list my documents.  When I clock on "test", it seems to load but the 
main body stays the same, as seen in the testdoc image.
- JP

**Comment by michael** [comment]
Can't see the screenshot. However, the docname should suffice.

polandj/{docname}

**Comment by polandj** [comment]
polandj/sample is the URI after I click on it.  However, when I see it 
in my list of documents it's called "Test".
- JP

**Comment by michael** [comment]
KK. Will look into that. Just give me some time. :)

**Comment by polandj** [comment]
Of course, no problem.
- JP

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
