### ISSUE TITLE
Refrain from using potentially conflicting variable/class/object names

### ISSUE THREAD

**Issue by smoofles** [substance/substance-legacy#14]
http://www.quackit.com/javascript/javascript_reserved_words.cfm 

The above list might be incomplete and, from what I know, the enforcing rules are far from strict, but it would be cool if keywords like "Document" or "document" would be omitted—would make substance work in Safari and likely prevent further issues down the road.

**Comment by michael** [comment]
There should be no problem when used within a closure. However, I'll look into those Safari issues.

**Comment by michael** [comment]
Now working in Safari again.
