### ISSUE TITLE
Page can no longer loaded

### ISSUE THREAD

**Issue by normanzb** [substance/substance-legacy#145]
open http://substance.io/normanzb/ with chrome

the document name keeps displaying 'loading...' and it never finished.

browser: chrome 15.0.874.121

platform: mac

(not sure if posted to the right place for substance.io issue

pls let me know if i am wrong)

**Comment by tDo** [comment]
Got the same problem on either Chrome (17.0.963.12) and Firefox (9.0.1) on OSX.
Haven't tried Safari or Opera yet but I guess this will lead to the same result.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
