### ISSUE TITLE
Document name can't be modified in edit mode

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#146]
The input field in the document tab should be editable and trigger document name changes.

**Comment by timjb** [comment]
I didn't notice that it is editable before. Thus, we should rethink this UI element.

**Comment by michael** [comment]
Yep, I don't like those "rich tabs" anymore. We'll introduce a menu with a fixed position, for switching between browser and editor views. Further controls will then live within the view scope. Will publish some screendesigns once I'm ready.
