### ISSUE TITLE
Unable to publish or add collaborators

### ISSUE THREAD

**Issue by jkap** [substance/substance-legacy#157]
I'm running Substance on my local machine and I'm unable to publish or add collaborators to any documents. I set up the installation using the [Substance Internals document](http://substance.io/substance/substance-internals). Is there some step I'm missing to get this to work?

Thanks in advance,
Josh Kaplan

**Comment by michael** [comment]
Is sendmail setup correctly on your machine? Collaborators need to confirm an email-invitation.

**Comment by jkap** [comment]
That's not relevant to the problem. The actual buttons to publish or add collaborators don't appear on the document page.

**Comment by michael** [comment]
Strange. They should show up at the actions panel on the left side, but only for the document's original creator.

**Comment by jkap** [comment]
Yeah, it works correctly on the version deployed at [substance.io](http://substance.io) but it doesn't work correctly on either of the two machines I've tried testing it on.

**Comment by jkap** [comment]
Not sure what was broken before, but it works correctly in the latest build.
