### ISSUE TITLE
Move and Delete buttons appear for collaborators without edit permissions

### ISSUE THREAD

**Issue by jkap** [substance/substance-legacy#165]
Collaborators who are only allowed to view still see the buttons to move and delete individual sections. When the delete button is pressed, the section deletes from the user's view but is not written to the database. When the move button is pressed, the "Move here" bars appear over every section. When it is pressed again, the "Move here" bars are replaced with "Insert Content" bars which are entirely non-functional.

This is preset in commit eb9d78c72d29.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring the all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
