### ISSUE TITLE
Unreachable document

### ISSUE THREAD

**Issue by thedod** [substance/substance-legacy#180]
I have [a document](http://substance.io/thedod/how-to-disable-signup-on-couchdb) with some botches in it (broken image uploads messed it up). I can't view it, and there's no other way to edit or even delete a doc.
I even have [the cleaned up json](https://gist.github.com/1702937), but no way (web or api) to import json into a doc :(

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
