### ISSUE TITLE
Login form not recognized by password manager (Firefox Sync)

### ISSUE THREAD

**Issue by joweiser** [substance/substance-legacy#184]
When using the login form at substance.io my password manager doesn't ask if this user/passwd combination should be saved.
Not too sure why this is happening but it might have something to do with the form parser not recognizing some heavy js lifting to generate the login form.
Unfortunately my password manager (Firefox Sync) doesn't allow my to manually add login data so I have to rely on a recognizable login form.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
