### ISSUE TITLE
Document identifier with spaces results in "Sorry, this name is already taken"

### ISSUE THREAD

**Issue by dasjo** [substance/substance-legacy#185]
just tried to create a new document with titles like
- My super long title do you like reading super long titles, no i don't
- My super long title do you like reading super long titles, no i don't 2

the resulting error message was misleading
- Sorry, this name is already taken.

**Comment by michael** [comment]
Will be fixed in 0.4.1

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series since we're getting closer to our 0.5.0 release featuring an all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
