### ISSUE TITLE
While in Dashboard... Document wouldn't open

### ISSUE THREAD

**Issue by gstangl** [substance/substance-legacy#19]
Wenn ich ein bestimmtes Dokument bearbeite, danach ins Dashboard wechsle um ein anderes Dokument zu bearbeiten, dann bleibt die Info immer bei "Loading document..." stehen. Kurz: Substance lädt dann das Dokument nicht.

Wenn ich ein Reload bei http://kollwi.substance.io/#load/kollwi/mon_ami mache funktioniert es auch nicht.  Erst wenn ich wieder zu http://kollwi.substance.io/ wechsle funktioniert es wieder.

Screenshot: http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-13%20at%2022.08.18.png

**Comment by michael** [comment]
Obsolete.
