### ISSUE TITLE
Updating user profile doesn't work

### ISSUE THREAD

**Issue by zauner** [substance/substance-legacy#190]
When changing my name, and hitting "Update Information", a POST request is sent to /updateuser, but keeps pending.

**Comment by ForbesLindesay** [comment]
ditto for trying to change my e-mail.  Also, is the e-mail really publicly visible? I haven't been able to find it when not logged in and I really don't think it SHOULD be publicly visible.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring the all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
