### ISSUE TITLE
Sticky Comments

### ISSUE THREAD

**Issue by jlank** [substance/substance-legacy#194]
When you write a comment and the next box for comment appears, it says <Enter Comment>, if you click "Add Comment" again you post the same text as your previous comment if you haven't changed or added new comment text.  The expected behavior is to not be able to submit an empty comment.

**Comment by joweiser** [comment]
I can confirm this behaviour, just experienced it myself.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring the all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
