### ISSUE TITLE
error when attempting to reopen a freshly-created document

### ISSUE THREAD

**Issue by edrex** [substance/substance-legacy#195]
I created my first document, then added an image, section, resource etc and deleted them. Then I closed the window tried to reopen the document. The document doesn't open and I get this error on the console:

```
Uncaught TypeError: Cannot call method 'substr' of undefined
(anonymous function)
b.each.b.forEach underscore.min.js:11
(anonymous function)
b.template underscore.min.js:29
s.util.tpl substance.min.js:8
s.views.DocumentLens.Backbone.View.extend.render substance.min.js:18
currentView
```

Browser: Chrome 20 dev Ubuntu

**Comment by edrex** [comment]
Here is the document exhibiting the behavior: http://substance.io/edrex/experiences-with-substance

I wasn't able to reproduce with another document.

**Comment by michael** [comment]
Mhh, that's bad :(. The most important thing is to find a way to reproduce it with a new doc. Please try again and let me know the steps, once you have it.

**Comment by mafo5** [comment]
Howto reproduce it on a local installation:
1. create a doc
2. create a section (just click the button - not filling anything into it)
3. click anywhere out of the section
4. close the window/tab
5. try to open the doc

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring the all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0
