### ISSUE TITLE
Flexible Cross-Origin

### ISSUE THREAD

**Issue by yocontra** [substance/substance-legacy#197]
Can we open up CORS for some resources?

Examples:
http://substance.io/documents/wearefractal (User data)
http://substance.io/wearefractal/debugging-native-modules.html (HTML export)
http://substance.io/wearefractal/debugging-native-modules.json (JSON export)
etc.

I think it would be nice to use this information from AJAX within the browser for visualizations or runtime grabbing of documents.

**Comment by michael** [comment]
Hey! Good idea definitely. At the end of the day, I'd also like to support cross origin resource sharing to support write operations as well for trusted sources.

However apart my day job, I'm now working 100% on the new Substance Composer, which will introduce an improved document format that can be collaboratively transformed through operations. We also want to introduce the concept of patches (cmp. Pull Requests on github) See: 

http://github.com/substance/composer
http://substance.io/michael/substance-okfestival

Being that said I don't want to invest too much time into Substance.io right now, as a lot of things will chance according to the improved document model.

However if you can come up with a pull request for that, I'd gladly merge it in. :)

Also (once the first working version is ready) help with the Subtance Composer, which will be MIT licensed, is highly appreciated. :)

-- Michael

**Comment by yocontra** [comment]
Awesome I'll start working on it now - there's an express plugin that allows you to specify CORS policies for different routes I'll look into using.
