### ISSUE TITLE
An em dash in the document causes exporting to fail

### ISSUE THREAD

**Issue by passcod** [substance/substance-legacy#204]
The most descriptive error message is the one the PDF option gives:

``` plain
Error: Child process exited with 1: convert: fromJSON: unknown constructor: EmDash
DataType {tycon = "Text.Pandoc.Definition.Inline", datarep = AlgRep
[Str,Emph,Strong,Strikeout,Superscript,Subscript,SmallCaps,Quoted,Cite,Code,Space,
LineBreak,Math,RawInline,Link,Image,Note]}
```

(breaks are mine, for legibility)

**Comment by michael** [comment]
Oh, we already fixed this.

https://github.com/substance/letterpress/commit/7f2129b22a4edfa0d952b67fffc00c8c71152239

Just forgot to deploy. Pls try again.
