### ISSUE TITLE
Unable to open document

### ISSUE THREAD

**Issue by mosch** [substance/substance-legacy#205]
While playing around with substance I got in trouble with my private document at http://substance.io/mosch/timeclock.

The error message is "Cannot read property 'key' of undefined", and it looks like its a problem while iterating through the sections:

https://github.com/substance/substance/blob/master/src/client/views/document.js#L18

```
g.type.key==="/type/section"
```

seems to fail.

**Comment by michael** [comment]
Seems like this one of the edge-cases we haven't yet dealt with.. They're pretty hard to spot. Can you reproduce the error somehow on a new doc? That actually be the only way I see to fix this permanently.

**Comment by michael** [comment]
Belongs to 0.4.0 series. Closing.
