### ISSUE TITLE
certain document names wouldn't work:

### ISSUE THREAD

**Issue by gstangl** [substance/substance-legacy#21]
Es ist ein "Conversation" Dokument. Die Benennung des Dokumentes hat nicht funktioniert.

Hat nicht funktioniert:
24hfirma
24_firma
24-firma

Hier Screenshot: http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-13%20at%2022.18.49.png

Hat funktioniert:
firma

Hier Screenshot: http://dl.dropbox.com/u/1033224/screenshots-kollwi/Screen%20shot%202011-01-13%20at%2022.20.57.png

**Comment by michael** [comment]
Now "-" within names and names starting with numbers are allowed.
