### ISSUE TITLE
Add some keyboard bindings for convenience

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#219]
- cmd+r (reload current site)
- alt+cmd+j (show webkit inspector)

We should also have shortcuts for navigating back and forward (browsing history) but probably not by binding to the backspace key (as browsers do it). Maybe shift+ctrl+alt + left/right. Not sure...

**Comment by michael** [comment]
Referring to this: https://github.com/substance/substance/issues/62

**Comment by obuchtala** [comment]
Accept.

**Comment by obuchtala** [comment]
Activating the web inspector programmatically seems to be impossible - at least not easily.
They have hidden everything into a private framework which can not be used...
Alternatively, one could have a look how Chrome adds its own webinspector... or even use that one...
Though, this is definitely not trivial.

**Comment by obuchtala** [comment]
Command + r works

**Comment by michael** [comment]
seems like this broke cmd+v for pasting stuff...

**Comment by obuchtala** [comment]
Fixed the latter a while ago.
