### ISSUE TITLE
Navigate using routes

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#220]
Found out the Backbone.Router is actually working.

```
document.location.href = "file:///Users/michael/Dropbox/projects/substance/index.html#new" triggers a new document for example.
```

I think we should just have a location textfield in the header, that holds the current navigation path and can be used to trigger routes.

Possible-Routes (we don't need to show the full url):
- `d5c54ee90910afc070714e12c4ba8132` - load doc by id
- `d5c54ee90910afc070714e12c4ba8132/section:5` - jump to section5 in the document
- `new` - triggers a new document

**Comment by obuchtala** [comment]
It would basically be possible to enable the browsing history...
Shall I activate it? How would you like to access it?

**Comment by michael** [comment]
Mhh.. not sure how I'd like to handle this.. I'm missing the browsers's address bar when developing. More than the browsing history. Maybe I'll add a fake adress bar so developing is easier.

**Comment by obuchtala** [comment]
I will add a navigation bar for development...

**Comment by michael** [comment]
No, I'll take care of this.
