### ISSUE TITLE
Substance App Icon

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#224]
Samo hat uns gschwind ein App Icon gmacht.

Drei Varianten zur Auswahl:

![](http://f.cl.ly/items/3M2j0j2n1s0B0O2Y3p2h/il-leone-icon.png)

![](http://f.cl.ly/items/292N0Z3K201J1o3M0i2y/flat-icon.png)

![](http://f.cl.ly/items/2K2k3M0S2B010U2i0G07/beige-icon.png)

@oliver---- was müssma tun damit das im build eingebaut wird?

@vectorsize like it?

**Comment by obuchtala** [comment]
> @oliver---- https://github.com/oliver---- was müssma tun damit das 
> im build eingebaut wird?

Hey,

I will address that the next days.

Cheers,
Oli

**Comment by vectorsize** [comment]
Looking good!!

just saw a very similar one though here:
http://echographapp.com/?utm_source=decknetwork&utm_medium=ad1&utm_term=evolved&utm_content=blue-clear&utm_campaign=iPhone5

**Comment by obuchtala** [comment]
Integrated into native app (OSX and Linux).

**Comment by michael** [comment]
Done. Closing.
