### ISSUE TITLE
The Substance Hub

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#226]
Now that we have a native app for manipulating documents, we'll also need a separate server component, the Substance Hub, which is responsible for hosting published documents.

Basically we need a Node.js app that offers:
- User registration / authentication
- Networks (published documents can be found in one or more topic-related networks)
- Document Snapshots (every version you publish will be stored on the hub, ready to be turned into beautiful HTML or other formats)
- User Interface for browsing networks/documents.
- A nicely designed read-only view of the document (e.g. http://substance.io/john/hello-world)

These are the most important features that we'd need along with the 0.5.0 release.

IN the future we might also want:
- Notifications
- Hosting of Realtime Sessions (collaborative editing)

**Comment by michael** [comment]
Now that we have a dedicated native editor we can optimise the web-version for distraction-free reading.

I liked this online book:

http://shapeofdesignbook.com/chapter06.html

Pretty nice typo and also responsive, so it looks nice on tablets and phones.

**Comment by yuchi** [comment]
I'll start working on it in the week, we'll refine the direction in a direct conversation

**Comment by michael** [comment]
Working on refining the document model today. I'll provide you a JSON representation of the document that you can use to render a static version. See you on Skype later tonight. 10pm CET you said, right?

**Comment by michael** [comment]
Also, pls send me a paragraph about yourself, so I can add you to the team page. :)

http://interior.substance.io/team/
