### ISSUE TITLE
Contextual toggles on top of the surface

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#228]
The Substance Text element should support a contextual menu that unobtrusively shows up every time a selection is made on the surface.

![](http://f.cl.ly/items/1929421v2g0X2T461a2g/Screen%20Shot%202012-10-30%20at%201.40.02%20PM.png)

We can use Surface's getAnnotations() API to find out which annotations are active for the current selection. The screenshot reveals there's a question annotation set already. Toggling an active annotation either removes it completely (if the current selection is a full match). If it's just an overlap we can just update the annotation accordingly.

E.g. consider the following situation:
- Strong Annotation at [50,10] - remember 10 is the offset, not the endpos
- Current Selection [55, 5]

When toggling off the `strong` annotation the annotation gets updated to [50, 5].

Edge cases to be discussed:
- selection is inside the boundaries of an annotation (this would cause a split up)

Some constraints (for Substance):
- `strong` and `emphasized` cannot be combined
- `suggestion` `question` `issue` annotations cannot be combined. We can look into ways of supporting this, but this constraint helps us keep the UI predictable.
- Those two categories can be combined, which means we can have character that are both, strong and tagged as suggestion.

**Comment by michael** [comment]
Alternatively, we could solve the whole thing by a contextual shortcut guide, appearing at the bottom of the screen.

![](http://f.cl.ly/items/193t1G0I2M3i1u1Q2Q26/Screen%20Shot%202012-10-30%20at%202.58.21%20PM.png)

After some first rough experiments I think we should have this, but probably not for the text annotation case. Instead we should guide the user through higher level operations such as:

In edit mode
- Add Text / Section / Image  (ALT+T, ALT+S, ALT+I)   new element will be attached after the element currently being edited
- ESC (return to structure level)

In structure mode
- 3 Nodes selected (reflect current node selection)
- Use alt + arrow up, or alt + arrow down to move selection
- ESC (return to document level)

Let me create some more sketches...

**Comment by vectorsize** [comment]
mmm Yeah I think i like the bottom tools better than the "tooltip" but there is no easy way to solve this otherwise for now. Why is this toolbar at the bottom though? I think it would look nicer if it is at the top same with as the document itself don't you think? I will also be more intuitive/easy to find.

**Comment by michael** [comment]
I think we should go with the inline toggles. We can see how it feels and if it's clunky we can just put it into a fixed toolbar.

Implementation:
- should be implemented in nodes/text/text.js
- on selection:changed event determine location of the annotation toggles (given a range [x,y] we can find out the screen position of the first character and just put the toggles below)
- active annotations should be highlighted (lots of edge cases!  however it should probably behave like MS word)
- extending overlapping annotations (see original post)

**Comment by michael** [comment]
Implemented.
