### ISSUE TITLE
Context Bar

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#229]
Now that our editor is fully keyboard driven, there could definitely be some guidance for new new users. @smoofles and I talked about a contextual action bar that reveals available operations based on the current element selection.  Based on that I did some sketches.

On the document level (Level 1)

![](http://f.cl.ly/items/2O2g3l0W0h17212I0y18/Screen%20Shot%202012-10-30%20at%204.49.35%20PM.png)

On the selection level (Level 2)

![](http://f.cl.ly/items/2a3r252n0H3B1z1F2G3M/Screen%20Shot%202012-10-30%20at%204.49.29%20PM.png)

On the node edit level (Level 3)

![](http://f.cl.ly/items/3V0V45253P140E0F2133/Screen%20Shot%202012-10-30%20at%204.49.23%20PM.png)

Goals / Questions:
- Make visible 3-layered navigation path (doc-level, structure-level, edit-level)
- Based on the context, make accessible actions
- We should think about how we can make keyboard shortcuts more prominent (not sure if tooltips are enough)
- Make clear that ESC key takes you one level higher
- How can we visually distinguish different levels?

**Comment by michael** [comment]
How does this feel when the doc is empty (e.g. there's just title/abstract set)?

![](http://f.cl.ly/items/160m2m3Z2j2N3F111K2X/Screen%20Shot%202012-10-30%20at%205.01.04%20PM.png)

**Comment by joweiser** [comment]
Very good idea! It would be interesting to run some usability test with a couple of potential users.
That would go a long way to show if those are even recognized ;)

Probably a more flashy hue (fitting the palette of course) would be helpful to guide the eye towards the bottom of the screen - like those alert bars showing up at the top of the screen on some websites to announce something (or like the lime green comment submit button here at github).

**Comment by michael** [comment]
Done.
