### ISSUE TITLE
Discussion Tools

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#230]
Design options for our Discussion Tool, that contextually displays relevant comments to certain parts of the document.

Classic tabs:

![](http://f.cl.ly/items/0J3Q3J1o2R302t3o0r2q/Screen%20Shot%202012-11-02%20at%2010.57.22%20AM.png)

Space efficient bullets:

![](http://f.cl.ly/items/2M3X34083e3C1p0r0K1b/Screen%20Shot%202012-11-02%20at%2010.57.43%20AM.png)

Requirements:
- General discussion tab (talk about a particular content element as a whole)
- One discussion thread per marker (colors: red, blue, green)
- Unlimited number of markers (space efficiency)
- Display comment count (or not)

What do you think?

**Comment by joweiser** [comment]
I think that strongly depends on your target audience.
Space efficient bullets look neat but UX is suffering severely - I don't know what those colors mean, the connection between the tab-button and the tab is lost (indicating which is currently active and that those circles are supposed to be tabs).
I'd view comment counts as something optional and thus rather not display them. My suggestion: If there are no comments then don't display the relevant tab.

And I'll vote for the classic tabs.

**Comment by michael** [comment]
True. It's just some rough interface ideas, that need to be verified. I'm not a designer so it's tough for me to fine-tune the stuff. However, I'm trying to make some good decisions regarding UX-flow.

Regarding colors: There's 3 marker types
- idea (green) make a suggestion
- blur (blue) something is unclear
- doubt (red) there's an issue with the corresponding text selection

Comments are optional, so you can just tag certain text passages as "doubted", without adding a comment. Not displaying a tab if there's no comment is not a idea I think, as there needs to be a way to "add the first comment".

**Comment by michael** [comment]
Usability testing... soon. :) We're at the early stage of making a good guess.

**Comment by michael** [comment]
Btw... Alternative UI Sketches appreciated. :)

**Comment by michael** [comment]
We've got a new layout for this.
