### ISSUE TITLE
Undo/Redo support for the RedisDocStore()

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#239]
I'd like to tacke undo/redo support in the coming days, as this is a very crucial feature I think. However, in order to implement this we need to get the backend ready as well.

I had in mind this approach:

Say we have:

c1, c2, c3, c4 (also persisted in the db)

Then I undo two operations by pressing cmd+z two times. To persist this change.. we need to update the master reference appropriately (to c3 after the first undo, and c2 after the second undo) the ops remain in the db (and are also loaded when accessing RedisDocStore.get)... UNTIL a new op c5 gets applied (which overwrites, resp. deletes c3,c4)

this will have the parent set to c2, so what we need to do in the db (and also in the doc model) is.. looking up the commis to be deleted (overwritten) if there are any.... I guess we can access the last commit in the db and check if it matches with the current master pointer...  if yes we can do a fast forward update... if not.. we need to walk back (by traversing the parent relationship) and delete commits until we hit the commit the master-ref points to.

@oliver----  does this make sense?

I guess we can implement the logic in javascript in the update method. but we need some sort of commit walking or deletion functionality on the low level interface. what do you think?

**Comment by obuchtala** [comment]
Makes sense.

Since today, all can be done in JS. RedisList provides these functions:
- size
- get(index)
- remove(index)

**Comment by obuchtala** [comment]
First iteration done.
Need collaboration to finish.

**Comment by michael** [comment]
My bro's band is practicing tomorrow afternoon... Meet at 3?

In the evening we could watch the new tarantino.. What do you think?

On 19.01.2013, at 20:20, Oliver Buchtala notifications@github.com wrote:

First iteration done.
Need collaboration to finish.

—
Reply to this email directly or view it on
GitHubhttps://github.com/substance/composer/issues/239#issuecomment-12459613.
