### ISSUE TITLE
Rename packaged app does not work.

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#241]
Just realized if I download the zip file containing the Substance.app, extract it, and then rename Substance.app to "Substance 2.app" it can't be started anymore.

**Comment by obuchtala** [comment]
Can not confirm this with the latest build. Maybe obsolete?

**Comment by michael** [comment]
Leme check a bit later...  

······································································
http://substance.io · http://quasipartikel.at
······································································

**Comment by michael** [comment]
Just showed it. It works when using "_" instead of spaces though.

**Comment by michael** [comment]
Looks like this means spaces in the app name are problematic.

**Comment by obuchtala** [comment]
File URL needs to be URL encoded.
Added encoding for " ".
If you see need for other characters occurring in a file system path that need URL encoding, reopen this issue.

For now closing,
