### ISSUE TITLE
Document Publishing and Metadata

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#243]
How should we store metadata such as `updated_at`, `document_name` or publishing information such as:
- `published_sha` - references the published commit sha.
- `published_at` - timestamp of last publication

---

In the future we may want to have an API for publications, so we can create multiple publications for the same doc, each referring to a specific version of the doc.

Question: Should we store a snapshot with every publication, or just refer to the commit sha? If we do just the reference we might get in troubles for undo actions.  E.g. if the user publishes commit 5, then executes undo 3 times and issues a new operation (e.g. insert heading) the document state cannot be reconstructed anymore because of the missing commits.

**Comment by michael** [comment]
Snapshot API:

To publish a document (or republish if it has been published already)

``` js
store.setPublication(documentId, publicationId, data);
```

`data` is the JSON representation of the doc (a snapshot), `publicationID` is like a unique version identifier... 

Internally.. a publication entry is created, a publication entry contains the following data:

``` js
{
  id: "2nd-edition",
  data: {nodes: {}, properties: {title: "Hello World"}},
  published_at: new Date(), 
  published_commit: "commit-5"
}
```

Could look like this: `documents:document_a:publications [REDIS ORDERED HASH, containing all publications ordered chronologically]

To retrieve a publication you can do:

``` js
store.getPublication(publicationID);
```

``` js
store.getLatestPublication(); // returns the most recent publication for that document.
```

``` js
store.getPublications(); // returns the most recent publication for that document.
```

**Comment by obuchtala** [comment]
Now we have implemented a version with "unnamed" publications, i.e., publications are stored in a list.

A publication instance looks like this:

```
{
  "created_at": new Date(),
  "data": snapshot
}
```

I.e., a publication contains a timestamp and a document snapshot.

store.createPublication(id, doc): creates a publication (appending to the list of publications)
store.listPublications(id): returns all publications
store.deletePublications(id): removes all publications
store.deletePublication(id, index): removes one specific publication.

**Comment by michael** [comment]
Done.
