### ISSUE TITLE
Critical: When commit contains special characters empty commit gets created, resulting in a corrupted document

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#251]
Reproduce steps:
1. Open a new doc.
2. Add a new Text Node
3. Paste the following content "Substance — A collaborative document editor". (commit gets applied locally but RedisStore does not create the commit properly)
4. Reload document  (have the console open, to see the resulting corrupted document before Exception is thrown.

**Comment by michael** [comment]
Shouldn't we create a testsuite for covering such cases? I guess it's a good idea to have the testsuite written in Javascript and run it against `RedisDocStore`.

**Comment by obuchtala** [comment]
Yep test-suite necessary.

**Comment by obuchtala** [comment]
Fixed.
