### ISSUE TITLE
document revisions

### ISSUE THREAD

**Issue by johannesjh** [substance/substance-legacy#26]
does substance have document revisions or does it not?
- the readme file states "Multiple saves result in multiple document revisions (a CouchDB feature) which means we get document versioning for free."
- the couch db wiki http://wiki.apache.org/couchdb/Document_revisions?action=show&redirect=DocumentRevisions reads: "You cannot rely on document revisions for any other purpose than concurrency control. Due to compaction, revisions may disappear at any time. You cannot use them for a client revision system."

=> so we get version numbers, but we can't (guarantee to be able to) access old versions?

**Comment by michael** [comment]
Good point. I wasn't aware of this when I was writing the Readme. However document revisions won't be supported in the first release (0.1) and will be added later along with other features:
- Realtime collaborative editing
- User Comments
- Document watchlist
- PDF export through LaTeX

I'll update the README asap. In the meanwhile here's a more recent, but still incomplete project description. http://edge.substance.io/#michael/substance

-- Michael

**Comment by michael** [comment]
Supporting revisions is now on hold, since we are dealing with a huge number of updates (save on literrally every keystroke). Creating a revision for every update would lead to huge amounts of data.

I could think of creating snapshots of documents, once a day (or manually triggered). Targeted for 1.0

**Comment by fabiand** [comment]
Maybe snapshots could be a variant of publishing. E.g. published revisions could be public snapshots, so snapshiots can be triggered manually now and again and shared with others when by publishing them.

**Comment by fabiand** [comment]
Okay, I suppose this is already noted in #120.

**Comment by michael** [comment]
Yepp. We'll improve that asap. Closing this ticket.
