### ISSUE TITLE
When logging in with the wrong credentials an ugly username/password prompt (for basic auth) is shown

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#264]
@oliver---- do we have a chance to avoid that?

**Comment by yuchi** [comment]
Don't worry it's my fault. The server is responding with a WWW-Authenticate header, which prompts the user agent to solve the situation as possible. WebKit is correctly prompting the username/pass.

I checked GitHub implementation, and even if it's called with a (wrong) Basic authentication no WWW-Authenticate is sent.

**Comment by michael** [comment]
So we'll fix this on the hub side?

**Comment by yuchi** [comment]
We have to.
