### ISSUE TITLE
SSL Troubles

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#266]
We exposed the API via https... but there's a problem with certificates:

```
https://hub.substance.io/api/v1/registerFailed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “hub.substance.io” which could put your confidential information at risk.
```

@oliver---- , can we turn off that check for certificate validity?

**Comment by obuchtala** [comment]
Could not find an easy way.
Solution is quite advanced...

I'd suggest to get a free ssl certificate here: http://cert.startcom.org/
