### ISSUE TITLE
External linked resources

### ISSUE THREAD

**Issue by vectorsize** [substance/substance-legacy#267]
The native app still points to resources outside the bundle. i.e. Substance.app/Redis/redis-server links to {composer-repo-clone}/ext/redisdb/bin/redis-server and Substance.app/Assets points to the composer cloned dir.

**Comment by michael** [comment]
@oliver---- we'll tackle this on friday for our final build.

**Comment by obuchtala** [comment]
Could not confirm. Can you check it again?

We've renamed the composer folder and moved the bundle into Applications and it worked just finel.

**Comment by vectorsize** [comment]
This is when I compile it myself.The easiest way to check this is by exploring the Substance.app package contents and see that inside the Contents directory for instance Assets is an alias. Also note I'm using the compiled app inside composer/build/app/osx – I hope I'm not grabbing the wrong one!

**Comment by obuchtala** [comment]
Yep, that is intentional.

The clean one is created using `make install` which creates the bundle into `dist` folder.

Is that looking better?
