### ISSUE TITLE
Clipboard content lost?

### ISSUE THREAD

**Issue by vectorsize** [substance/substance-legacy#273]
After copying some content and adding a new node to paste the copied content, the clipboard seems to be empty?
This might be related to the pasting mechanism we implemented with the surface, we might want to share the paste container among all the surfaces to avoid this.

**Comment by michael** [comment]
Can you add steps to reproduce. This error did not happen to me so far.

**Comment by vectorsize** [comment]
Forgot to specify that this happens when you delete the old node that you copied from and then try to paste.
Try writing a paragraph, select all, cut, then you delete the node, and create a new one and paste, the content is gone with the previous node somehow, the inspector doesn't complain.

**Comment by michael** [comment]
Figured out cutting isn't possible at all. Probably a Surface issue. We should look into that, it's quite annoying.
