### ISSUE TITLE
After hitting Backspace at the beginning of a text node, cursor should jump into previous text node.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance-legacy#276]
Generally: "Backspace" should be the undo button for "Enter". If I now hit Enter, a new text node will be created, cursor is at the beginning of it. If I hit Backspace, I want to jump to my previous position in the previous text node and new textnode should be deleted.

**Comment by michael** [comment]
This doesn't scale with other nodes (like images). I'd rather leave deletion explicit as we have it now, so people don't accidentally kill nodes.
