### ISSUE TITLE
I can't edit my documents after quitting the Composer app

### ISSUE THREAD

**Issue by streetlib** [substance/substance-legacy#291]
I've downloaded the new client v 0.1.0 and i've created 2 documents.
I've quitted the app and reopen it, but my documents are vanished and i cannot edit those documents anymore.
I've tried to resinc my documents using the icon on the right, but it seems not working.

**Comment by michael** [comment]
Sorry for the late reply. I missed that new issue. Can you open the javascript console for me so I can see how the error looks like.

In order to do that you have to activate debug features:

In the OSX terminal execute:

```
$ defaults write quasipartikel.Substance WebKitDeveloperExtras -bool true
```

Then restart the Composer, right mouse click -> inspect element and open the log panel (^8)

**Comment by michael** [comment]
Another thing you can try is resetting the user database (but first try to find the error message using the console so we can reconstruct the error). 
1. Quit the app
2. `rm $HOME/Library/Application\ Support/Substance/substance.rdb`
3. Restart the app
4. Click sync (so you get your server copies again)

**Comment by streetlib** [comment]
Hi Michael,
as you may see on substance HUB, i've created and published 3 documents:

http://hub.substance.io/fedeonline

but on my app i can see only the last doc: "La mia birra".

I've reset my user database as stated in your previous mail, but after sync
procedure i see only the last doc. The first two docs are vanished from the
app and i cannot edit them anymore.

The log seems ok, no error reported as you may see in the attached
screenshot.

2013/2/6 Michael Aufreiter notifications@github.com

> Another thing you can try is resetting the user database (but first try to
> find the error message using the console so we can reconstruct the error).
> 1. Quit the app
> 2. `rm $HOME/Library/Application\ Support/Substance/substance.rdb
> 3. Restart the app
> 4. Click sync (so you get your server copies again)
>    
>    —
>    Reply to this email directly or view it on GitHubhttps://github.com/substance/composer/issues/291#issuecomment-13185630..

## 

## 

Federico Pugnaloni
Project Manager Mobile Apps

Simplicissimus Book Farm - www.simplicissimus.it
Email\GTalk: federico.pugnaloni@simplicissimus.it
Skype: castor007 - Twitter: http://twitter.com/fedeonline
Mobile: +39 340 0630321

**Comment by michael** [comment]
I see. There might be some confusion around two separate concepts (two independent workflows):
- Replication (synchronize/back up the full editing history with substance.io)
- Publishing (a snapshot gets pushed and gets visible on http://substance.io/explore)

So I guess what happend is that you did not trigger a sync (after all three documents have been created). For our alpha version we decided to turn off auto-sync so errors can be better spotted and the user has full control which information goes to the server. Not ideal in terms of usability yet (we're aware of this).

**Comment by michael** [comment]
I see you replicated two documents see here:

https://substance.io/api/v1/documents/list/fedeonline

https://substance.io/api/v1/documents/get/fedeonline/b731a68b2a4aa96479cd6e8806f58a6c
https://substance.io/api/v1/documents/get/fedeonline/535a4b026b8453e879d2755925326e76
- we opened up read access to replicated documents for debugging purposes, so these links won't be available to unauthorized users in the future.

**Comment by streetlib** [comment]
Ok, i've understand. I suppose i've published the first two documents but
not synced them. Now i'm aware of the two separate workflows.

Thanks

2013/2/6 Michael Aufreiter notifications@github.com

> I see. There might be some confusion around two separate concepts (two
> independent workflows):
> - Replication (synchronize/back up the full editing history with
>   substance.io)
> - Publishing (a snapshot gets pushed and gets visible on
>   http://substance.io/explore)
> 
> So I guess what happend is that you did not trigger a sync (after all
> three documents have been created). For our alpha version we decided to
> turn off auto-sync so errors can be better spotted and the user has full
> control which information goes to the server. Not ideal in terms of
> usability yet (we're aware of this).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/substance/composer/issues/291#issuecomment-13186801.

## 

## 

Federico Pugnaloni
Project Manager Mobile Apps

Simplicissimus Book Farm - www.simplicissimus.it
Email\GTalk: federico.pugnaloni@simplicissimus.it
Skype: castor007 - Twitter: http://twitter.com/fedeonline
Mobile: +39 340 0630321

**Comment by vectorsize** [comment]
Also, bear in min @simplicissimus that if you hold all your content inside one single long node, auto-save might not happen. Text nodes are meant to be short sections of your documents and autosave is only triggered when your text node loses focus, so what might have happened is that the document didn't have time to be stored even once.
