### ISSUE TITLE
Cleanup / Versioning strategy

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#294]
FYI: I did some cleanup and removed all legacy branches on the composer repo. Now we have:

`master` (latest confirmed code preparing for the 0.2.0 release)
`image-support` (will be merged with master once completed)
`production` (version that is currently shipped)

as far as maintaining the production branch is concerned, let's just do critical fixes which go along with a patch release for the composer (e.g. v0.1.1). However ideally we can avoid that until 0.2.0 is out. will save us time and energy. Also we need to setup some logic in the composer so people are forced to use the latest client. When opening the composer we need a message:

"This alpha version of the Substance Composer is no longer supported. Please download the latest version here.".

**Comment by yuchi** [comment]
We can also block the old Composer by updating its credentials on the production Hub :lame:

**Comment by michael** [comment]
Yeah, why not. The problem we have is we need a proper way of notifying the user. With our current build this is not supported.

I'd suggest implementing a little hello service, which just checks the protocol. We could offer some backward compatibility in the future but for now this is just complicating things.

```
http://substance.io/api/v1/hello?composer=0.1.0&protocol=0.2.0
```

and this returns either:

``` js
{
  "code": "ok",
  "message": "Enjoy the Substance."
}
```

Or: 

``` js
{
  "code": "please_upgrade",
  "message": "There's a newer version of the Substance Composer. It's highly recommended to upgrade."
  "upgrade_url": "http://link.to/new/composer"
}
```

Or: 

``` js
{
  "code": "client_deprecated",
  "message": "Your client is no longer supported. Please get the latest one."
  "upgrade_url": "http://link.to/new/composer"
}
```

**Comment by yuchi** [comment]
Food for thoughts: auto-updating composer? @oliver---- is it even possible?

**Comment by obuchtala** [comment]
Everything is possible ;)
Don't know if I can switch binaries underneath a running Substance instance.
I'll think about it.
