### ISSUE TITLE
For code content type enter should trigger newline.

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#301]
Probably we need to adapt the Surface appropriately.

**Comment by vectorsize** [comment]
I thought we might use codemirror for code implementation?? did you change your mind?

**Comment by michael** [comment]
Eventually code mirror makes sense. However for now we can just derive the textish interface. And also use our markers with no extra efforts. I will consume some time to translate our marker interface to codemirror. Let's wait on syntax highlighting etc, it's not a big blocker during editing. And we can add syntax highlighting for the rendered version on the hub.

**Comment by michael** [comment]
Also don't underestimate the powers of the Surface. :) It makes a good foundation for a code editor as well. And it's much lighter. We only need a fraction of the features CodeMirror provides.. also i don't know how multiple instances scale.

I'd prefer smooth editing of larger portions of code over syntax highlighting for the time being.

**Comment by vectorsize** [comment]
Yeah you are right, functionality is in place™ :)

**Comment by michael** [comment]
There are some minor issues with line-breaking still, so for the sake of proper code support this might be a good chance to fix them. Will open tickets on the Surface repo as soon as I have steps for reproduction.

**Comment by michael** [comment]
Fixed this already.
