### ISSUE TITLE
Implement Autosync™

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#302]
Make autosync happen. I guess it's a good default to backup everything, in smaller increments.

Only drawback: This violates the privacy aspect. So we should no longer promote Substance docs are private until they are published.

In future we should ask the user how he'd like to handle replication.
- Option 1: Backup private documents (CONVENIENT)
- Option 2: Only backup published documents (SECURE)

**Comment by vectorsize** [comment]
Regarding this, I would say, autosave locally rather than auto-sync/auto-push, maybe we are talking about different things here? Also if we can set if a document is public or not we can still have pused documents that doesnt show publicly

**Comment by michael** [comment]
No I was just referring to "you have everything under control and nothing goes over the wire without your permission". Of course we can ensure on the server side that no unauthorized access can happen.

**Comment by michael** [comment]
However we need this autosync stuff for supporting a collaborative workflow. As soon as you invite a collaborator it must be synced so others can interact with the doc.

**Comment by michael** [comment]
Implemented. Closing.
