### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by vectorsize** [substance/substance-legacy#304]
Now that we started adding annotation types and after the discussion @michael @yuchi and I had a few days ago, I've put some time sketching how I see the annotation interaction could be more consistent.

At the moment we started adding two different workflows for annotations, one using the right sidebar to add comments/annotations for certain types and an inline workflow to add urls for the link type. Where this works as it is right now, I think we should aim for consistency in terms of UI so here's an idea I propose using the inline method.

![idea](https://f.cloud.github.com/assets/1661889/180101/ecc6a3f4-7c21-11e2-804e-dbd9553dba76.png)

This proposal suggests that the _toolbar_ would stick on top of the document frame, when one option is selected the corresponding form would unfold under the selected line (in a similar way as gh inline code comments)

This is how then adding a link url would look like:

![link-1](https://f.cloud.github.com/assets/1661889/180108/48c7cca0-7c22-11e2-81b5-f944160b385f.png)

Also this could have more complex options per annotation type… Here's an example:

![link-2](https://f.cloud.github.com/assets/1661889/180110/67db08fa-7c22-11e2-803c-8c25a7b5e05c.png)

I forgot to add a cancel btn but I think this illustrates what I meant.
Please let me know what you think, I wanted to get that out of my head, and feedback is very welcome!

**Comment by yuchi** [comment]
You could collapse the OK/Cancel button some how (and rename OK to "Update annotation" in my opinion) to reduce space usage.

That said... I **_love**_ this proposal.

EDIT: Also, as a reminder (to myself mostly), `href` and `alt` say nothing to an unexperienced user. We could use the _progressive reduction_ thing to collapse "Address to link to" into "href" if an icon is provided to preserve the interface meaning to the user.

**Comment by vectorsize** [comment]
Thanks @yuchi ! I agree regarding href and such, not sure about the icon though, if this will be one day available for plugins we might want to minimize the number of assets required per plugin…

here's another possible combination

![link-3](https://f.cloud.github.com/assets/1661889/180445/3000ebc0-7c31-11e2-8e22-b432f08215d7.png)

Although this one could feel a bit strange since it opens two times, one when you select, and second when you pick an annotation type, that might feel strange.

All this possibilities seem discussable to me, also I would like to hear @michael 's feedback since he already went trough a lot of research regarding theses type of interactions in the first Substance version.

Aslo note I haven't though about the rest of the application UI and the implications on it when switching to such workflows (i.e how the right sidebar interacts and keeps meaning and connection to this other part of the screen etc)

**Comment by michael** [comment]
Liking the idea of removing floating elements. I have some concerns with this proposal though, but they're hard to express in text. However, as discussed with @vectorsize in the chatroom, let's make this part of a general UI overhaul, ideally when we all sit together in one room. :)

The current UI is solid enough for the next alpha release, so I'm trying to focus on other priorities first.

**Comment by yuchi** [comment]
Another idea: we should create a different UI for toggle-buttons (strong. emphasis..) and toggle-buttons with a "drop-down" (lnk, suggestion...). The first type could moc the Android toggles:

![togglebutton](https://f.cloud.github.com/assets/646609/184574/8e12cf44-7ce0-11e2-9c17-caa0bf770ec7.png)

**Comment by vectorsize** [comment]
I'm not sure I understand what you mean here @yuchi , do you mean that we need a UI difference between the buttons that will have extra options (_dropdown_ in your words) from the ones that just affect the text (_toggle_ in your words)?

**Comment by yuchi** [comment]
Exactly. I couldn't explain it better.

**Comment by michael** [comment]
This is going to be a Substance.Camp task :)
