### ISSUE TITLE
how to unpublish if original doc was deleted from the local store

### ISSUE THREAD

**Issue by thosmos** [substance/substance-legacy#310]
I created a doc, published it, deleted it locally, and now I can't unpublish it.

**Comment by michael** [comment]
That's a known issue. Will be fixed in the next alpha release. When deleting a doc all publications need to be removed too.

**Comment by michael** [comment]
I'm going to tackle this in the coming days. I think I'll deal with it on the replication level, which means if you delete a doc offline, removal of all publications happens on the next sync. It may be useful to include the pending-deletion information in the user interface, so you see you have uncommitted local changes.

**Comment by michael** [comment]
How about just flagging documents as deleted (in the UI) instead of hiding them immediately? This would allow users to undelete docs and also we can use the same "local changes" terminology.

**Comment by michael** [comment]
Covered in a testcase: https://github.com/substance/tests/blob/master/002-remove-published-doc/composer.js

Oliver, I assigned you to this ticket.

**Comment by michael** [comment]
This has been fixed. See updated test case: https://github.com/substance/tests/blob/master/tests/002-remove-published-doc/test.js

**Comment by michael** [comment]
Keep in mind doc will get removed+unpublished on next sync.
