### ISSUE TITLE
Make sure the last change always gets persisted

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#311]
E.g. when you don't confirm a change by clicking outside the editing area.

Described in the last comment of #291.

**Comment by obuchtala** [comment]
Is this a low level problem?
I.e., before quitting the app some js code needs to be called?
Or can be handled within js?

**Comment by michael** [comment]
Not sure. But it looks like the blur event doesn't get fired on the content area when the app is closed. Maybe I can hook into a  "before:quit"  event. But probably you need to expose that somehow.

**Comment by michael** [comment]
Obsolete with new infrastructure.
