### ISSUE TITLE
Problems with build script

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#313]
Each time after a restart of my machine, I can't open the Composer locally (The dev build not the packaged app). It seems stuff from `/tmp/` gets deleted. Maybe we should put stuff somewhere else.

Also I've renamed `store/src/store.js` to `store/src/redis_store.js` which breaks the build process. One of the shell scripts or CMakefiles need to be adjusted. I've re-created a copy named store.js so the build goes through. However we should get rid of this.

**Comment by obuchtala** [comment]
Closed by a33ad35c.
