### ISSUE TITLE
Trouble building under Linux

### ISSUE THREAD

**Issue by adob** [substance/substance-legacy#314]
I'm getting the following error when making 'composer':

```
[ 50%] Building CXX object app/gtk/CMakeFiles/substance.dir/main.cxx.o
/home/alex/proj/substance-composer/app/gtk/main.cxx:2:37: fatal error: wx/webkit_jsc_extension.h: No such file or directory
compilation terminated.
make[2]: *** [app/gtk/CMakeFiles/substance.dir/main.cxx.o] Error 1
make[1]: *** [app/gtk/CMakeFiles/substance.dir/all] Error 2
make: *** [all] Error 
```

Where does the file wx/webkit_jsc_extension.h come from?

**Comment by obuchtala** [comment]
The linux build is not working at the moment.
Actually, the currently available webkitgtk is on a rather old version where
XMLHttpRequests do not work properly - which makes it useless for us.
We are waiting until a newer webkitgtk is bundled.

**Comment by michael** [comment]
Next release will be web-only. Native builds will chip-in again at a later time.
