### ISSUE TITLE
Complete Uninstall

### ISSUE THREAD

**Issue by timfall** [substance/substance-legacy#317]
It would be nice to either include a complete uninstaller to remove **all** the files created by substance, or at least a list of these files at this point.

**Comment by michael** [comment]
Currently you should be safe by deleting `~/Library/Application Support/Substance`.

**Comment by timfall** [comment]
Great! Would it be helpful to include a quick uninstall script somewhere? I'be happy to dash one off.

**Comment by michael** [comment]
One question remains though: Why would you ever want to uninstall Substance? ;-)

**Comment by timfall** [comment]
Nice. ;)
For the future, it might be nice to follow Steam's example. They have a LaunchAgent to see if the app gets trashed and prompts to remove the other things.

**Comment by michael** [comment]
Next release will be web-only. Native builds will come back later this year.
