### ISSUE TITLE
Document fails to save on quit

### ISSUE THREAD

**Issue by kimslawson** [substance/substance-legacy#318]
There is no confirmation on quit, and also, the currently edited document does not save on quit.

To reproduce:
1. create a new document
2. type a bunch of stuff you'd like to keep.
3. Quit Substance.
4. Relaunch Substance.
5. Experience disappointment.

**Comment by michael** [comment]
True. We're aware of this. We need to install a native before:exit hook that confirms and saves the change before the app gets closed.

**Comment by michael** [comment]
Did you build the latest version yourself or were you using the pre-built binary?

**Comment by kimslawson** [comment]
I did not build from source, I used the binary downloaded from the substance.io site.
