### ISSUE TITLE
Normalise inheritance style across projects

### ISSUE THREAD

**Issue by andreypopp** [substance/substance-legacy#330]
Not sure if this is the right place to start a discussion but will try.

Recently I started to use Substance components (Data, Store and Document specifically) and was quite confused by inconsistent usage of inheritance mechanisms.

Packages use different names for prototype factories — `__prototype__` (Store,  Data) and `Prototype` (Document, Surface). I think it's not only worth to normalise its usage but also to switch to inheritance mechanism which uses intermediate constructor function (like Backbone and CoffeeScript does). I see you already have `inherits` function in `substance-util` package.

What do you think if I submit a series of pull requests to Substance projects to migrate to `inherits` inheritance? I interested specifically in Document, Data, Store, Chronicle and Operator projects.

**Comment by michael** [comment]
Hey! You'r right. We started with using **prototype** and moved over to Prototype, since it's nicer to read. We don't want to use an inheritance helper since it obfuscates things for the user. We decided it's better to write one or two lines of code more.

We'd welcome your help in normalising everything to use Prototype over **prototype** and other things you might find to be inconsistent. After we discussed them. :)

**Comment by andreypopp** [comment]
> We don't want to use an inheritance helper since it obfuscates things for the user. We decided it's better to write one or two lines of code more.

That's interesting, I'm thinking in exactly the opposite way — I as a newcomer to substance codebase was a bit surprised to see how inheritance is implemented.

Backbone, Node.js (via utils stdlib modules) and a couple of other js libs implement inheritance via some helper. There's a reason for that — setting up a prototype chain is an implementation detail as for this specific use case of mimicking classical OO and not using prototypes directly.

I believe using the helper defined in substance-utils will make Substance codebase much more friendlier especially for novice programmers.

**Comment by michael** [comment]
I've been there too for a long time. However I realised it's a big source of confusion, since people don't know what's going on behind the curtain (happened to me too) by being explicit you get the understanding about how the prototype chain is setup.

We'd like to stick with it until there's better support in Javascript itself. (ES6...) Can't wait for this to be available:

```
class SkinnedMesh extends THREE.Mesh {
  constructor(geometry, materials) {
    super(geometry, materials);

    public identityMatrix = new THREE.Matrix4();
    public bones = [];
    public boneMatrices = [];
    ...
  }

  update(camera) {
    ...
    super.update();
  }
}
```

**Comment by andreypopp** [comment]
Heh... ok, this makes usage of substance components with CoffeeScript harder but I think I will workaround this with some helper:

```
class Page extends from(Document)
  ...
```

**Comment by michael** [comment]
Yeah we don't use Coffeescript mainly for the same reason. We'd like to be close to the metal. Javascript has it's flaws.. but it's all we have at the moment. Dart/Coffeescript etc. are all adding additional complexity, which negatively affects the stacktrace for debugging etc.

**Comment by andreypopp** [comment]
> Yeah we don't use Coffeescript mainly for the same reason. We'd like to be close to the metal. Javascript has it's flaws.. but it's all we have at the moment.

Yeah, that's true — if you want to create a friendly environment for external contributions it is better to keep it simple.

> Dart/Coffeescript etc. are all adding additional complexity, which negatively affects the stacktrace for debugging etc.

Not true regarding CoffeeScript — you can use source maps for debugging and it doesn't introduce any additional runtime behaviour.

**Comment by andreypopp** [comment]
I submitted pull request and they were accepted so I'm closing this issue.
