### ISSUE TITLE
Inline and block code

### ISSUE THREAD

**Issue by brianshumate** [substance/substance-legacy#342]
Currently the code formatting which renders < code > tags which are inline elements, but it would also be nice to have a block element (i.e. < pre >) as well. I'm not sure how this could be implemented with respect to the UI, but I think it would be very handy especially for technical documents.

**Comment by michael** [comment]
Actually we have a codeblock type:

![screen shot 2014-04-16 at 01 58 00](https://cloud.githubusercontent.com/assets/2931/2714597/e228b01e-c4f9-11e3-857d-f45f3e0e9233.png)

**Comment by brianshumate** [comment]
Aha, I had not noticed it in there since I'm accustomed to seeing such things as individual button-ish elements in other WYSIWYG style editors.

Thank's for pointing that out!

**Comment by michael** [comment]
Maybe that's an issue with respect to usability. We have the concept of a text type... which can either be heading, paragraph, list, codeblock. We have a little bit of space problem too.. so having list and code block types in the text type selection looked reasonable. Do you have a sample/screenshot how codeblock toggles are displayed in other editors?

**Comment by brianshumate** [comment]
Oops, probably closed this prematurely and was thinking the exact same thing! :)

I'll dig up some other editor screenshots to compare how such things are handled in them and share those here.

**Comment by brianshumate** [comment]
Yes, the convention seems to be to put < pre > in the drop down with headings, and except in the case of the TinyMCE demo, i didn't really find much for handling code.

So TinyMCE puts both code and pre into drop downs but splits them out based on block or inline types:

Code:

![tinymce_code](https://cloud.githubusercontent.com/assets/77563/2714761/37a6c1e0-c4fd-11e3-8420-d15d7955b47d.png)

Pre (formatted):

![tinymce_pre](https://cloud.githubusercontent.com/assets/77563/2714797/d1935200-c4fd-11e3-8551-6916fa161cf2.png)

Other editors are similar with respect to putting pre/formatted/code block into drop down:

CKEditor puts both pre and code into different drop downs:

Code:

![ckeditor_code](https://cloud.githubusercontent.com/assets/77563/2714787/84eb29a0-c4fd-11e3-8e80-f5f2fbd2c6b3.png)

Pre/formatted:

![ckeditor_formatted](https://cloud.githubusercontent.com/assets/77563/2714788/8f09aef2-c4fd-11e3-9e8f-342ccf0a7ddd.png)

Aloha editor also has Pre with headings:

![aloha_preformatted](https://cloud.githubusercontent.com/assets/77563/2714790/9ffd7e5a-c4fd-11e3-9a09-8a63f0124ccb.png)

So I suppose in summary, everything is pretty good UI wise, and just needs some documentation, which I'll get to work on! :)

**Comment by michael** [comment]
Closing since it is UI-related stuff. Such issues should go to https://github.com/substance/ui/issues in future.
