### ISSUE TITLE
Mismatch between editor preview and rendered content

### ISSUE THREAD

**Issue by brianshumate** [substance/substance-legacy#343]
There is a bit of a mismatch between a document using code formatting in Composer and the rendered result.

Composer shows code or monospaced text as a block, whereas the rendered output is inline. This is related to #342.

Attached are some screenshots showing an example which is a poem that I'd like to have specific monospaced formatting that demonstrates this issue.

Here's the preview:

![screen shot 2014-04-15 at 12 43 31 pm](https://cloud.githubusercontent.com/assets/77563/2714598/e65f6696-c4f9-11e3-8ad4-0f9c2de16b13.png)

Here's the rendered result:

![screen shot 2014-04-15 at 12 43 41 pm](https://cloud.githubusercontent.com/assets/77563/2714600/f7ce0504-c4f9-11e3-9349-adf6df8187c5.png)

**Comment by brianshumate** [comment]
So in this one, it is possible to highlight a block of text and assign the code button vs. code block to it, which produces the above result if that makes sense.

Perhaps this is sort of also surfacing a UI issue with respect to the two distinct means with which one can specify code formatting as well, since I did not expect to see code block in a list containing heading levels.

Either way, I think that specifying in detail how one can format content with screenshots of the UI elements would be a good addition to the user guide? If so I'll definitely work on adding that to the guide. :)

**Comment by michael** [comment]
Closing, as not relevant to Substance core. This won't fix because that Substance compiler component is no longer under active development.
