### ISSUE TITLE
getRangeAt index errors on undo operations

### ISSUE THREAD

**Issue by brianshumate** [substance/substance-legacy#344]
Getting Uncaught node.js Error  when performing undo operations in Composer with ⌘ Z

```
Uncaught node.js Error 

Error: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at eval (/Applications/Substance Composer.app/Contents/Resources/app.nw/node_modules/substance-surface/src/surface.js:269:26)
```

Steps to reproduce:
1. Open Substance Composer and start a new document
2. Paste a paragraph of text
3. Format pasted text as code block
4. ⌘ Z to undo
5. ⌘ Z again
6. Error

**Comment by obuchtala** [comment]
Confirmed. Will put it high priority.

**Comment by obuchtala** [comment]
Fixed.

Will be shipped with beta 2 :)
