### ISSUE TITLE
More flexible creation date specification

### ISSUE THREAD

**Issue by brianshumate** [substance/substance-legacy#345]
It would be helpful if the date selector widget in Substance Composer were a bit more flexible in specifying creation date. For example, I would like to work with documents I created years ago, and the arrows alone would make that pretty tedious.

Screen shot to show which UI element I am referring to:

![date_picker](https://cloud.githubusercontent.com/assets/77563/2727931/c493ff3c-c5e3-11e3-938e-446033fdd3a8.png)

Would it be possible to add a different widget or even make the date value directly editable?

**Comment by michael** [comment]
Not applicable to the framework part.
