### ISSUE TITLE
Application chrome not visible on 11" Macbook Air

### ISSUE THREAD

**Issue by blueclock** [substance/substance-legacy#350]
When I open the Composer application, the top chrome with the min/max/close buttons is not visible and the buttons in the top bar are partially obscured.

See attached screenshot.

![substance io-on-air-11](https://cloud.githubusercontent.com/assets/586174/3005798/d999f6fc-ddf3-11e3-9230-439e573ce92c.png)

**Comment by michael** [comment]
Will be fixed in next version. Thanks for pointing out.

**Comment by michael** [comment]
Not related to framework code. Closing.
