### ISSUE TITLE
Issue with incremental index update

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#353]
An array update operations kills index.

``` js
var tx = this.props.writerCtrl.doc.startTransaction();
tx.set([this.props.subjectReferenceId, "target"], subjectIds);
tx.save();
```

While graph object is updated accordingly, the index returns invalid results after:

![image](https://cloud.githubusercontent.com/assets/2931/6996194/9adf3da4-db78-11e4-9799-4326a5569ea1.png)

Reproduce:
- activate a subject_reference
- tick a new subject
- switch to subjects-panel

**Comment by obuchtala** [comment]
If possible, try to fix it yourself.

**Comment by michael** [comment]
Ok i will try. just don't fully understand yet, how the index updates work (also in combination with ops and transactions).

Our of curiousity, when a transaction document is modified, are there also copies of the indexes of the original doc?

**Comment by obuchtala** [comment]
Yup, the transaction doc is totally independent. These index copies are created in  https://github.com/substance/substance/blob/next/src/document/transaction_document.js#L19

In both, indexes are called explicitly from graph, e.g., https://github.com/substance/substance/blob/next/src/data/graph.js#L133

**Comment by michael** [comment]
Fixed.

https://github.com/substance/substance/commit/b07a006ada500191ece201fbe00104093ea189f7
