### ISSUE TITLE
Cursor change (after click) sometimes not reflected

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#363]
This is a timing-related issue, I think related to the short delay after we rerender a text node (while during typing we just let contenteditable do its thing).

Reproduce:
- type fast in a paragraph and quickly click into next paragraph

-> often the cursor will move back into the previous paragraph (once the rerender of the text node happens)

**Comment by obuchtala** [comment]
Won't fix.
As we will never have full control as render is async, the events may come async.. there is no chance without a brutally heavy event-sequencer.
