### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by greaber** [substance/substance-legacy#365]
Hi!  I am working on a web site to crowdsource content that can contain annotations and other semantically rich elements.  We don't want to require users to write in a special markup language, but we are undecided about whether we want to store all of the semantic elements internally using markup or store them as external annotations that would reference a region of the document by character range.  In either case, we will want to render documents in a highly customized way, e.g. by making certain annotations appear in the margin by the text they annotate.

We have been really confused by the contenteditable landscape and are even considering using textareas since we really don't need to do a lot of styling of the content itself, but it would be nice to at least have italics and maybe a few other things.

It sounds like your philosophy at substance is in many ways similar to ours!  Do you think that any of your software could be useful to us (or do you have other recommendations)?  I cloned a couple of the substance projects but didn't immediately see how to get them working.  The substance package itself seems just to be a library without much documentation outside of comments.  Some of the other packages on github, such as journal and writer seem more like applications, but I got errors when I tried to install and run them.  In the case of writer, the README, which seems to be about a program named archivist-composer, mentions using a program named substance to fetch dependencies, but I don't know what that program is.

**Comment by michael** [comment]
Hey can you get in touch via email? You can find contact details here: http://substance.io/about/

And yes, I think Substance could be for you! I'm aware things look a bit confusing from the outside. We use our stack mostly in client projects at the moment and don't find a lot of time for documentation and tutorials. The good news is that our editing foundation is really solid after almost 5 years of development. I hope we can soon follow up with a more complete solution: The Substance Journal release it not far away, and it could be a great starting point for projects like yours. We already have implemented entity tagging for a digital-archive project. Here's a demo using a stubbed-backend.

http://cdn.substance.io/archivist-composer/

Pls say hi via email, and let's try to make a short call or so?

Cheers, Michael
