### ISSUE TITLE
Containers are not updated properly when doc.set API is used to manipulate the document.

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#366]
E.g. in Substance Journal or Archivist Writer do this:

``` js
doc.set(["paragraph_1", "content"], "foo"]);
```

The containers (resp. views are not updated)

The relevant code in Substance.Document is a bit fragile. I fixed some things regarding propagating ops to `_updateContainers` but still it doesn't update accordingly to those ops.

See: https://github.com/substance/substance/commit/3f5b979c2a19d15cccc85d3e2a17abe6431a6332

@oliver---- can we make this a higher priority to fix? I need this to work because in Substance Journal I want to set things like image urls etc. using that api.

**Comment by obuchtala** [comment]
I assume, the problem is, that atm the default way is to use transactions.
The low-level changes do not trigger the comlex document:change events.
We would need to introduce a mode without transactions....

**Comment by michael** [comment]
Omg, is it possible that I didn't use a transaction for this? 

Mhh.. but still.. if you have an atomic operation, without the need for a transaction we should have the same events triggered.

**Comment by obuchtala** [comment]
Closing this.

We enforce transactions now when used in the App.
