### ISSUE TITLE
Create remove-whitespace transformation

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#377]
We use this as a showcase for the documentation.

**Comment by Integral** [comment]
https://github.com/substance/archivist-writer/commit/5260c35fb3863141d97ff5ed2e2dc6b583eefb38
My first tool :)

In fact this is find and replace tool, I just tell it to convert all double spaces to one space.

What is also not perfect that it is performs transactions for every occurrence while find and replace usually is one operation which can be undone with one undo execution.

**Comment by michael** [comment]
very nice!

What we should do is to write a transformation searchAndReplace that works on a text property level. Like that gets a path and searchStr and replaceStr.

Then we could have another searchAndReplaceInContainer, which gets a containerId, searchStr and replaceStr and then applies the basic searchAndReplace on each container node.

Problem I see is that we somehow need to determine the text-ish node components. Some nodes have multiple components like a figure that has title and caption.

**Comment by michael** [comment]
Closing in favor of #388
