### ISSUE TITLE
Edge case with container annotations when selection includes last character of a paragraph

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#382]
Consider this selection

![image](https://cloud.githubusercontent.com/assets/2931/8648745/88140662-2963-11e5-853d-96f555e4dff8.png)

Now hit the backspace button.

-> Error happens in deleteNode transformation:

![image](https://cloud.githubusercontent.com/assets/2931/8648768/bd61b8e6-2963-11e5-9125-dd2fc346d31b.png)

**Comment by obuchtala** [comment]
Fixed.
