### ISSUE TITLE
Edge case: selecting two paragraphs fully and hit backspace makes problems

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#384]
Selection is lost and warnings are shown on the console.

Reproduce using substance/starter, and make the following selection:

![image](https://cloud.githubusercontent.com/assets/2931/8648933/7fee5ec2-2965-11e5-8bb5-cc6e6a41f4e1.png)

Hit backspace:

![image](https://cloud.githubusercontent.com/assets/2931/8648952/a28295c0-2965-11e5-8d19-67980ec3c4c0.png)

**Comment by obuchtala** [comment]
Fixed.
