### ISSUE TITLE
There are some broken docs around.

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#43]
Check why this is the case. Example: /#inatikat

**Comment by michael** [comment]
Found a workaround, so the docs can be at least loaded. Problem is that the associated user object does not come with the document subgraph.

Is /user/inatikat actually in the DB?

**Comment by snusnu** [comment]
huh?

**Comment by michael** [comment]
For some reasons users disappear (are no longer in the db), while their documents are still there. Kinda strange.....

**Comment by michael** [comment]
Fixed. There was a problem at user registration, which caused the user not to be saved in the DB. Concerned users should re-register with the same username.
