### ISSUE TITLE
Make newly added subjects available without a complete page reload

### ISSUE THREAD

**Issue by snusnu** [substance/substance-legacy#44]
Currently, when adding new subjects for a document and then clicking on the browse button, you need to do a manual page reload to have the newly added subject be displayed in the list of filters.

While at it, why are these things called "subjects" inside the editor, and "filters" in the browser? can't we unify the wording? maybe not ...

**Comment by michael** [comment]
Duplicate. https://github.com/michael/substance/issues#issue/34

We can have arbitrary many facets (type: "/type/attribute"). Filters is just the generic name for all of them. Subjects is a concrete filter(category), and so the newly added "Entities contained" is.
