### ISSUE TITLE
Issue with placeholders

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#49]
There's wrong behavior when you do the following steps:
1. Click into an empty section (the placeholder gets replaced with the cursor)
2. Switch the window (OSX level)
3. Click into the Substance window again

=> The placeholder « Enter Section Name » stays there and is now treated as regular content.

Possible solution: Reset the selection when window gets out of focus.

**Comment by timjb** [comment]
I've fixed this sometime in proper.

**Comment by michael** [comment]
True.
