### ISSUE TITLE
Browsers do not save credentials

### ISSUE THREAD

**Issue by schinckel** [substance/substance-legacy#59]
Because of the 'clever' way the login/authentication form works, browsers (Safari, at least) are not able to pick up on me having entered my credentials, and therefore cannot store them in my Keychain.

This means people are less likely to use single-use passwords, as they will need to remember them, rather than have an automated system enter them.

Please consider finding some way to have the browser aware of the username/password, so it can offer to save it. Even if a regular (non AJAX) request is required, it's worth it.

**Comment by michael** [comment]
Not sure if this belongs to AJAX. I guess it doesn't work because the involved markup isn't in the DOM when the page finishes loading. Will have a look at this. Thanks for pointing it out.

**Comment by joweiser** [comment]
The behaviour changed a little bit.
Username/password combinations are now recognized (FF12) while submitting the login form and can be saved by the credential manager.
When visiting the site and typing the username the passwords isn't fetched.
