### ISSUE TITLE
Deleted document still shows "Loading ... " 

### ISSUE THREAD

**Issue by sverma** [substance/substance-legacy#73]
http://substance.io/documents/saurabhverma/testdocument

response is 

{"status":"error","error":"not found"}

but when i hit 

http://substance.io/#saurabhverma/testdocument/
I get "Loading .. " on document_tab div 

 <div id="document_tab" class="tab hidden" view="document" style="display: block;"> Loading...</div> 

I'm not a ajax guy , but it should show "not found .. " here ? I guess

**Comment by michael** [comment]
True. Will fix that.
