### ISSUE TITLE
Support for LaTeX

### ISSUE THREAD

**Issue by keks** [substance/substance-legacy#74]
In your [introduction paper](http://substance.io/#substance/substance) you say " With Substance, we want to give [...] Scientists [...] an open platform for writing and publishing their articles." Scientists need formulas, formulas need LaTeX (or something similar).

Is this planned? Do you have a better solution for formulas?

**Comment by michael** [comment]
Hey! There's already a rudimentary implementation of a LaTeX renderer for exporting Substance Documents. See http://letterpress.substance.io. We'll soon extend this and allow on-the-fly pdf generation, as it's a crucial feature.

Re. your question: Supporting formulas specified in LaTeX syntax would be an option. I could see a WYSWYG- formula editor too (see https://github.com/sdiehl/wise), but this will certainly take time and does not have priority.

But what about maintaining formulas outside of the system and make them available as SVG or MATHML? I'm about to add support for embedding of SVG content. We do not attempt to create a feature-heavy application that does everything, so I consider this approach as a legitimate option.

As of now you can already embed formulas as images using an online equation editor. 

See http://substance.io/#michael/Math

**Comment by keks** [comment]
I only meant including Latex in a document, not exporting to latex, sorry for not being precise.

"I could see a WYSWYG- formula editor too (see https://github.com/sdiehl/wise), but this will certainly take time and does not have priority."
Great! Maybe I'll look into it a bite when I have time.

"We do not attempt to create a feature-heavy application that does everything"
Of course not. But IMHO formulas are an important feature, and being able to change them in-place would be a great plus. Also this is mandatory if you have a paper with more than 10 formulas.

But for the moment using the generator will have to be enough, though.

**Comment by michael** [comment]
Another way that might be interesting for scientific writers would be the possibility of publishing regular LaTeX projects to Substance. I think of a command utility that watches for changes on .latex files, and push it to Substance when modified.
We're already working on such a utility, but targeting markdown for the time being.

And just in case you run into something that could be useful for us, just let me know.

-- Michael

**Comment by michael** [comment]
Consider this for 1.0

**Comment by keks** [comment]
this might be a good idea: http://www.math.union.edu/~dpvc/jsMath/

**Comment by ghost** [comment]
I believe the state of the art in this is Mathjax (http://www.mathjax.org/), but ideally you want to just read in LaTeX and store and display it as MathML with browsers doing the rendering.

**Comment by michael** [comment]
Would love to see someone adding a Formula-Nodetype to Substance based on Mathjax for rendering. 

Marius? :)

**Comment by ghost** [comment]
I'll add it to my to do list. Don't hold your breath, but I'll try. ;-)

**Comment by michael** [comment]
Yeah! :)

Ping me if you're ready. Will be happy to get you started. :)
