### ISSUE TITLE
Two line title of section

### ISSUE THREAD

**Issue by agrublev** [substance/substance-legacy#81]
I have a section with a very long title and when it goes on two lines it looks poorly. 

This is a really easy fix just adding a css rule
# document h1, #document h2, #document h3, #document h4, #document h5 {

font-weight: normal;
margin: 2em 100px 0 100px;
padding-bottom: 1em;
line-height: 1.6em;    /\* this line <------- */
}

Anyways, I also wanted to mention how amazing this is and I highly support your work!

**Comment by michael** [comment]
Thanks for that. Just added your patch. It will be available on the next deploy.. (among other things: lots of layout improvements are on the way :) )
