### ISSUE TITLE
new app: node server.js throws error: _design/queries not found

### ISSUE THREAD

**Issue by stepheneb** [substance/substance-legacy#9]
I cloned substance and followed the readme to make a new app.

First there was an error because couch-client wasn't installed:

```
$ node server.js

node.js:66
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
Error: Cannot find module 'couch-client'
    at resolveModuleFilename (node.js:274:15)
    at loadModule (node.js:236:22)
    at require (node.js:300:16)
    at Object.<anonymous> (/Users/stephen/dev/javascript/substance-git/lib/adapters/couch_adapter.js:1:81)
    at Module._compile (node.js:357:32)
    at Object..js (node.js:365:14)
    at Module.load (node.js:288:27)
    at loadModule (node.js:260:14)
    at require (node.js:300:16)
    at Object.setAdapter (/Users/stephen/dev/javascript/substance-git/lib/data.js:48:21)
```

I installed couch-client with npm and then got this error:

```
$ node server.js
31 Dec 18:44:15 - Your node instance does not have root privileges.This means that the flash XML policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
31 Dec 18:44:15 - socket.io ready - accepting connections
Loading schema...

/Users/stephen/dev/javascript/substance-git/lib/adapters/couch_adapter.js:126
            throw('_design/queries not found.');
            ^
_design/queries not found.
```

node/npm status:
    $ npm list installed
    npm info it worked if it ends with ok
    npm info using npm@0.2.11-5
    npm info using node@v0.3.3-pre
    async@0.1.7           Higher-order functions and common patterns for asynchronous code    =caolan installed latest remote
    coffee-script@1.0.0   Unfancy JavaScript    =jashkenas installed latest remote stable javascript language coffeescript compiler
    connect@0.5.2         High performance middleware framework    =creationix =tjholowaychuk installed latest remote
    couch-client@0.0.3    A Simple, Fast, and Flexible CouchDB Client    =creationix installed latest remote
    cradle@0.3.1          the high-level, caching, CouchDB library    =cloudhead installed latest remote couchdb database couch
    dnode@0.4.2           Transparently call remote callbacks    =substack installed latest remote rpc rmi remote network communication websockets socket.io
    docco@0.3.0           The Quick and Dirty Literate Programming Documentation Generator    =documentcloud =jashkenas installed latest remote stable documentation docs generator coffeescript
    express@1.0.0         Sinatra inspired web development framework    =tjholowaychuk installed remote framework sinatra web rest restful
    express@1.0.1         Sinatra inspired web development framework    =tjholowaychuk installed latest remote framework sinatra web rest restful
    eyes@0.1.6            a customizable value inspector    =cloudhead installed latest remote inspector debug inspect print
    html5@0.2.5           HTML5 HTML parser, including support for SVG and MathML foreign content    =aredridel installed latest remote
    htmlparser@1.7.3      Forgiving HTML/XML/RSS Parser in JS for _both_ Node and Browsers    =tautologistics installed latest remote
    jake@0.1.5            =mde installed remote
    jake@0.1.8            =mde installed latest remote
    jsdom@0.1.22          CommonJS implementation of the DOM intended to be platform independent and as minimal/light as possible while completely adhering to the w3c DOM specifications.    =tmpvar instal
    lazy@1.0.3            Lazy lists for node    =pkrumins installed latest remote lazy
    nodeunit@0.5.0        Easy unit testing for node.js and the browser.    =caolan installed latest remote
    npm@0.1.27-12         A package manager for node    =isaacs installed package manager modules install package.json
    npm@0.2.12-1          A package manager for node    =isaacs installed remote package manager modules install package.json
    opts@1.2.1            Command line argument parser written in the style of commonjs. To be used with node.js    =mazzarelli installed latest remote
    recon@0.0.6           Keep a network connection alive by reconnecting repeatedly    =substack installed latest remote network reconnect connection
    ronn@0.3.5            markdown to roff and html converter    =kapouer installed latest remote markdown roff man documentation
    socket.io@0.6.3       The cross-browser WebSocket    =rauchg =Tim-Smart installed latest remote
    traverse@0.2.3        Traverse and transform objects by visiting every node on a recursive walk.    =substack installed latest remote
    underscore@1.1.3      Functional programming aid for JavaScript. Works well with jQuery.    =documentcloud =jashkenas installed latest remote util functional server client browser
    vargs@0.1.0           practical variable argument handling    =cloudhead installed latest remote argument arguments
    vows@0.5.2            Asynchronous BDD & continuous integration for node.js    =cloudhead installed remote testing spec test BDD
    vows@0.5.3            Asynchronous BDD & continuous integration for node.js    =cloudhead installed latest remote stable testing spec test BDD

**Comment by michael** [comment]
The readme is currently outdated. The Couchapp is no longer needed. What you need to do is to seed the db. $ node db/seed.js

**Comment by stepheneb** [comment]
I created a new database named substance in couchdb and then ran seed.js:

```
$ node db/seed.js
Couch seeded successfully.
Start the server: $ node server.js
```

The following documents are in substance:

```
/user/demo
/type/user
/type/text
/type/section
/type/image
/type/document
```

But starting the server generates the same error:

```
/Users/stephen/dev/javascript/substance-git/lib/adapters/couch_adapter.js:126
        throw('_design/queries not found.');
        ^
```

**Comment by michael** [comment]
Interesting. Need to look into it. In the meanwhile you can add the design document manually. You need to set {_id: "__design/queries", views: {} }

**Comment by michael** [comment]
Things are a bit rough atm. I've changed the whole internals lately. I'll update the instructions as soon as things get stable again.

**Comment by stepheneb** [comment]
When I used futon to create a new document in the substance db with
    id = "__design/queries" 
futon reports: _Only reserved document ids may start with underscore._

I instead created on with only one underscore:
    id = "_design/queries" 
which worked but now I get this error when starting the server:

```
1 Jan 04:05:56 - socket.io ready - accepting connections
Loading schema...
ERROR: Couldn't fetch schema
```

**Comment by michael** [comment]
Please pull the latest code from the repo — the error message for your particular problem should now be displayed.

```
// Seeding should create the _design/queries document as well. Data.adapter.flush() 
// is responsible for this.
$ node db/seed.js
```

That's the corresponding code
https://github.com/michael/substance/blob/master/lib/adapters/couch_adapter.js#L29

**Comment by michael** [comment]
I've updated the README and moved the couchdb configuration to config.json again. You need to set couchdb_url as shown in the example config file https://github.com/michael/substance/blob/master/config.json.example. Then execute the seed script. Good luck.

**Comment by stepheneb** [comment]
I deleted and recreated the db 'substance' in futon.
Copied the example into config.json.
Ran: `node db/seed.js` successfully.
Ran `node server.js` and got a more descriptive error that ended with: `_design/queries not found`.
Then created `_design/queries` by hand.

Now I get a startup error trying to load the schema '`graph.fetch({type: '/type/type'}` in server.js here: https://github.com/michael/substance/blob/master/server.js#L480

```
$ node server.js
1 Jan 14:22:21 - Your node instance does not have root privileges.This means that the flash XML 
  policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
1 Jan 14:22:21 - socket.io ready - accepting connections
Loading schema...
ERROR: Couldn't fetch schema
not_found
```

There is no document `'/type/type'` in the couch db. Is that supposed to be created when the db is seeded?

**Comment by michael** [comment]
`/type/type` is a recognized built in type. So we do not need to have it in the DB (as yet). Hm...  really strange that _design/queries is not created for you.

Error handling is a big issue atm. I'll improve it until we've identified the particular error that hits you. Will ping you when updates are ready.

**Comment by michael** [comment]
You should probably get a better error message now.

**Comment by stepheneb** [comment]
Same results ...

Deleted and re-created database 'substance' in couchdb.

Updated to most recent commit:

```
[substance-git (master)]$ git log -1
commit bfce53d60e1dc9c20ce381f054c443c3b3733f46
Author: michael <ma@zive.at>
Date:   Sun Jan 2 13:19:24 2011 +0100

    First version of the KollWi Theme.
```

Seed the db (_design/queries not created):

```
[substance-git (master)]$ node db/seed.js 
Couch seeded successfully.
Start the server: $ node server.js
```

Start the server and get the error that _design/queries can't be found:

```
[substance-git (master)]$ node server.js 
2 Jan 11:51:59 - Your node instance does not have root privileges.This means that the flash XML policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
2 Jan 11:51:59 - socket.io ready - accepting connections
Loading schema...

/Users/stephen/dev/javascript/substance-git/lib/adapters/couch_adapter.js:126
            throw('_design/queries not found.');
            ^
_design/queries not found.
```

Create _design/queries by hand and restart server:

```
[substance-git (master)]$ node server.js 
2 Jan 11:52:30 - Your node instance does not have root privileges.This means that the flash XML policy file will be served inline instead of on port 843. This will slow down initial connections slightly.
2 Jan 11:52:30 - socket.io ready - accepting connections
Loading schema...
ERROR: Couldn't fetch schema
not_found
^C
```

Error thrown here `graph.fetch({type: '/type/type'}` in server.js:

```
console.log('Loading schema...');
graph.fetch({type: '/type/type'}, {}, function(err) {
  if (err) {
    console.log("ERROR: Couldn't fetch schema");
    console.log(err);
  } else {
    console.log('READY: Substance is listening at http://'+(config['server_host'] || 'localhost')+':'+config['server_port']);
    app.listen(config['server_port'], config['server_host']);
  }
});
```

Am using couchdb 1.0.1, nodejs head (v0.3.3-pre), and npm v0.2.13-3

**Comment by michael** [comment]
Can't reproduce the error on my system :/. I'm using the versions:

```
dubbook:substance michael$ npm list installed
npm info it worked if it ends with ok
npm info using npm@0.2.8-1
npm info using node@v0.3.0-pre

async@0.1.7           =caolan active installed latest remote
coffee-script@0.9.6   =jashkenas active installed remote
connect@0.5.2         =creationix =tjholowaychuk active installed latest remote
couch-client@0.0.3    =creationix active installed latest remote
dnode@0.4.2           =substack active installed latest remote
docco@0.3.0           =documentcloud =jashkenas active installed latest stable remote
express@1.0.1         =tjholowaychuk active installed latest remote
eyes@0.1.6            =cloudhead active installed latest remote
lazy@1.0.3            =pkrumins active installed latest remote
npm@0.2.8-1           =isaacs active installed
recon@0.0.6           =substack active installed latest remote
socket.io@0.6.3       =Tim-Smart =rauchg active installed latest remote
traverse@0.2.3        =substack active installed latest remote
underscore@1.1.3      =documentcloud =jashkenas active installed latest remote
vargs@0.1.0           =cloudhead active installed latest remote
vows@0.5.2            =cloudhead active installed remote
npm ok
```

I'm afraid you'd need to do some debugging yourself....

There's not so much code involved when calling `graph.fetch()`. You'd need to check:

Data.Graph#fetch()
https://github.com/michael/substance/blob/master/lib/data.js#L1161
CouchAdapter#readGraph()
https://github.com/michael/substance/blob/master/lib/adapters/couch_adapter.js#L70

I'm pretty sure the error happens on CouchClient#get. Watch for occurrences of `db.get()`.

-- Michael

**Comment by michael** [comment]
Not sure, but https://github.com/michael/substance/commit/91cc98ee45eef38c7ae5aed99ad73b55c963a333 could have fixed your issue.

**Comment by michael** [comment]
Did it solve your problem? 

One more thing: You need to use the "kollwi" theme for the moment (to be set in config.json). The default theme is currently broken.
