### ISSUE TITLE
Keyboard scrolling problems

### ISSUE THREAD

**Issue by botker** [substance/substance-legacy#90]
Although I have caret browsing disabled in Firefox 5, the document exhibits caret browsing behavior with an invisible caret. The result is that keyboard scrolling seems broken. For those of us who avoid using the mouse, this makes it extremely difficult to read the document.

To reproduce, go to a document in FF5 and press and hold the down-arrow. Note that the document does not immediately scroll down. Since the cursor is invisible, press and hold the shift key to select and highlight text while pressing the down-arrow. Once the cursor reaches the bottom of the window, scrolling will finally work. Then switch to the up-arrow to see it de-select text. The effect is akin to interacting with text in a textarea, and completely inappropriate for trying to read a document.

Similarly, page-up, page-down, home, end, and the spacebar exhibit related behaviors.

Also, loosely related, middle-clicking a link fails to open it in a new tab. Basically I want to disable javascript just so I can read the document. I don't really care if I'm able to annotate it.

The document I'm trying to read is: http://substance.io/#michael/data-js

**Comment by michael** [comment]
You're right. Very strange. Do you have an idea what could cause caret browsing to be enabled. I'm using contenteditable=true for inline-editing. But you're looking at the doc in view-mode, so that shouldn't be a problem.

Will investigate that.

**Comment by botker** [comment]
I haven't looked into it much, but I wonder if FF5 actually allows you to unbind the default keydown behavior. That can't be right.

BTW, data.js looks potentially awesome, and kudos for making use of contenteditable.
