### ISSUE TITLE
trouble creating documents in crome

### ISSUE THREAD

**Issue by bleeppurple** [substance/substance-legacy#91]
- logging in OK
- unable to create a new document
  = on create

'an error occured check your input'

**Comment by michael** [comment]
Did you just register a new user? There's a bug which drops the session after registering. So you'd need to reload the page, login again and it should finally work. 

I've fixed this today and will roll it out asap. Until then, hit reload.

**Comment by bleeppurple** [comment]
Thanks Michael that's exactly what happened...
great peace of software thanks
