### ISSUE TITLE
Support for Footnotes

### ISSUE THREAD

**Issue by dbeinder** [substance/substance-legacy#92]

**Comment by michael** [comment]
I don't think we'll support footnotes as a first class feature. Footnotes result from the limitations of paper, which we do not have in an electronic document. However we can consider footnotes in one of the output formats (e.g. LaTeX/PDF) to represent the URL's of links.

**Comment by dbeinder** [comment]
Well, nearly every scientific text/paper needs source citations. But it's good practice in other types of articles as well to put additional detail info into footnotes. Of course when reading a document online in the 'endless paper mode', real footnotes at the end of the page are impractical, so maybe it would be better to show them in a box when clicking/hovering on them with the cursor. In this case 'Remarks' or 'Annotations' is probably a better name for the feature I thought of.

**Comment by michael** [comment]
Real references/ (citations vs. transclusions) are planned for 0.5.0. Stay tuned. :)

(inspired by Ted Nelson http://www.youtube.com/watch?v=En_2T7KH6RA)

**Comment by jokull** [comment]
I disagree with the notion that footnotes exist because of real estate issues. Some authors use them extensively to pad their narrative with additional or optional information. 

Excellent that they're being added!

**Comment by nichtich** [comment]
Please don't mix footnotes with citations and references. Footnotes are structuring elements such as paragraphs. Citations are one special type of references, which are both often used in footnotes.

**Comment by michael** [comment]
Also here. We going a new path with annotations. We'll cover that usecase.. but I think we well call it simple a "Note" annotation. Then it can be rendered as you wish. As a tooltip, as a footnote when exported for print etc.

**Comment by nichtich** [comment]
Ok, I begin to understand. So "note" will be a type of annotation in the document, which can be mapped to "footnote" in the presentation layer. We should be careful not to confuse levels of description. I am still curious to get a clean descriptions of how the levels (network of nodes, schema of node types, mapping to editor and output formats) are connected to each other.

**Comment by michael** [comment]
Yep. me too. That's what we need to figure out. A good clean interface is key. It takes time. And we take that time. :)
