### ISSUE TITLE
Local install pdf generation

### ISSUE THREAD

**Issue by maacl** [substance/substance-legacy#95]
Is there a way to enable pdf generation using a local install. The link appears to be broken but I guess that since letterpress is a webservice it should be possible to configure the local install to use http://letterpress.substance.io/ ?

**Comment by michael** [comment]
you can set "letterpress_url" to http://letterpress.substance.io. However since the letterpress service takes an URL, your local instance must be reachable from outside.

Alternatively you can setup your own letterpress instance. All you need is a working LaTeX installation (e.g. MacTex on OSX).

**Comment by maacl** [comment]
I get:

Letterpress is listening at http://localhost:4004
Caught exception: Error: ENOENT, No such file or directory
'tmp/_document_mac_25ee827197e43d2b6371434ee4a71349'

when trying trying to use a local letterpress install.

/mac

On Mon, Jul 18, 2011 at 4:03 PM, michael
reply@reply.github.com
wrote:

**Comment by maacl** [comment]
I have this:

"letterpress_url": "http://localhost:4004",

in my config.json. Shouldn't that be right?

**Comment by michael** [comment]
I guess you need to create the tmp directory by hand. (within letterpress root)

**Comment by maacl** [comment]
Thanks - that did the trick.

/mac

On Tue, Jul 19, 2011 at 4:36 PM, michael
reply@reply.github.com
wrote:
