### ISSUE TITLE
Version control / Undo

### ISSUE THREAD

**Issue by maacl** [substance/substance-legacy#96]
It appears that the all changes are persisted to the database, but is there any way to access previous versions through the UI or any undo functionality beyond the most recent node edits?

**Comment by michael** [comment]
Not yet. CouchDB's revisions can't be used for versioning (they're just there for resolving conflicts). However versioning is definitely something we wanna add in a future version.

**Comment by max-mapper** [comment]
here are a couple couchdb revisioning strategires for reference: 

http://blog.couchbase.com/simple-document-versioning-with-couchdb
https://github.com/phred/recollection

**Comment by michael** [comment]
Version 0.5.0 will be storing the full doc history, so we'll be good here.
